### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by raphaelavalos** [PettingZoo-Team/PettingZoo#151]
Hello,
Would it be possible to add a link to the docs (maybe with readthedocs) ? :)
Thanks !

**Comment by justinkterry** [comment]
The documentation is here:

https://pettingzoo-team.github.io/PettingZoo/

The last things we're working on before doing a proper 1.0 release is finishing cleaning that up, and some misc fixes to butterfly environments. The documentation used to all be .md files, and we're still in something of the transitional phase there.

**Comment by raphaelavalos** [comment]
Nice! Maybe you could put the link in the read me or the about section of the repo, I spent quite some time looking for it :)

**Comment by justinkterry** [comment]
Done
