### ISSUE TITLE
Enable HTTPS on pettingzoo.ml

### ISSUE THREAD

**Issue by thomasfsteeples** [PettingZoo-Team/PettingZoo#157]
The website pettingzoo.ml is currently only accessible over HTTP. Enabling HTTPS access is a relatively straightforward thing to do nowadays (via, say, [Let's Encrypt](https://letsencrypt.org/)). Please could HTTPS be enabled for the domain?

**Comment by justinkterry** [comment]
The site is hosted by github pages. We've been trying to fix it for a few days, but there's been various problems. It's on our list.

**Comment by weepingwillowben** [comment]
https://www.pettingzoo.ml now works. 

https://pettingzoo.ml still gives a certificate error.
