### ISSUE TITLE
Better performance test

### ISSUE THREAD

**Issue by ndyashas** [PettingZoo-Team/PettingZoo#170]
Hi!. I've noticed that the current performance testing at ```pettingzoo/tests/performance_benchmark.py``` runs for only 5 seconds and is run only once. Wouldn't it be better if the test is run multiple times with a longer runtime? That way we can report the results as ```value ± error```.

I'm happy to make a PR if this is valid.

**Comment by weepingwillowben** [comment]
Thanks for bringing this up. After you mentioned it, I found a bug in the performance test which is fixed by #171

**Comment by weepingwillowben** [comment]
But in general, while 5 seconds doesn't seem like that long of a time, for classic environments, this is long enough to play dozens of games, and for most other environments, the complexity of the calculations seems to remain fairly constant throughout play, so the number of samples doesn't matter that much. 

We also want to keep the travis tests running quickly. So any change should not affect the ci_test's runtime.

**Comment by ndyashas** [comment]
Understood!. Also, I think it would be better to use the ```time.process_time()``` rather than ```time.time()```. As mentioned [here](https://docs.python.org/3/library/time.html#time.process_time), ```time.process_time()``` does not include time elapsed during sleep. Thus, a (very slightly) better measure compared ```time.ime()```.

I will make some local changes and let you know if I get consistent reports on the ```value ± error``` reporting method I mentioned earlier. If they have similar inconsistencies over multiple runs, then it would be better to leave out that complexity.

**Comment by weepingwillowben** [comment]
I merged the fix, make sure to use it in any local tests. I will await the results with interest.

**Comment by ndyashas** [comment]
I have made the modifications while keeping the overall test time same, However, while testing the inconsistency seems to still be as they were in the previous version. I have also added some benchmarking reliability tests as given [here](https://pyperf.readthedocs.io/en/latest/cli.html#pyperf-check).

I have also used ```time.process_time()``` instead of ```time.time()```. PR #172
