### ISSUE TITLE
Improved install instructions and __version__

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#176]
A few bumps I've found while starting to use PettingZoo:

1. Need improved install instructions in README and [website](https://www.pettingzoo.ml/). For example, `pip install pettingzoo` and/or `conda install pettingzoo`. Also, some description of install with "extras", e.g. do I need to run `pip install pettingzoo` or `pip install pettingzoo[all]`?

2. There seems to be an inconsistency between `requirements.txt` and `setup.py`. When I try to work through the [ray pettingzoo example](https://github.com/ray-project/ray/blob/master/rllib/examples/pettingzoo_env.py) I get the error
`ModuleNotFoundError: No module named 'pygame'` which had me confused because `pygame` is clearly in the [`requirements.txt`](https://github.com/PettingZoo-Team/PettingZoo/blob/master/requirements.txt#L2). I then looked an `setup.py` to find the `extras` param. Is `requirements.txt` actually used? If not, can it be removed for clarity?

3. I can't see a way to easily check the version of PettingZoo I have installed. My normal workflow of `import pettingzoo; print(pettingzoo.__version__)` gives error `AttributeError: module 'pettingzoo' has no attribute '__version__'`

Thanks for development on this library!

**Comment by weepingwillowben** [comment]
I made a PR to address this. We definitely don't want new users to be turned away by little bumps like this!

So I added the __version__ and instructions in the readme on installing with the extras.

The one thing I'm not sure what to do about is the requirements.txt. I guess I'm not exactly sure what bumps people will run into if it is not there.

**Comment by justinkterry** [comment]
I may have mentioned this before, but if you're using PettingZoo regularly, you may want to take a look at SuperSuit: https://github.com/PettingZoo-Team/SuperSuit. It's a helper library for PettingZoo and Gym environments that we use a ton internally.

**Comment by rallen10** [comment]
@weepingwillowben The changes to README look sufficient to address my concern, therefore you can ignore my comment about `requirements.txt`. Thanks for the changes! I'll close this issue
