### ISSUE TITLE
NameError: name 'policy' is not defined

### ISSUE THREAD

**Issue by marcasteroid** [PettingZoo-Team/PettingZoo#183]
Just trying to run introductory example on main page and get this error:

NameError: name 'policy' is not defined

for

`action = policy(observation)
`

**Comment by justinkterry** [comment]
The example uses a bit of dummy code. A policy refers to an ML model that you've learned.

**Comment by marcasteroid** [comment]
Thank you

**Comment by mumu-star** [comment]
> The example uses a bit of dummy code. A policy refers to an ML model that you've learned.

Could you give me an example? I still don't understand

**Comment by elliottower** [comment]
See the tutorials on our site, we have various examples of training machine learning models (neural networks, for example)

Here’s a simple-ish example (see the line model.predict https://pettingzoo.farama.org/tutorials/sb3/connect_four/)
