### ISSUE TITLE
Examples of RLlib QMIX trained in PettingZoo environments (e.g. prison)

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#184]
In very much the same vein as [this MADDPG issue](https://github.com/PettingZoo-Team/PettingZoo/issues/182), I was wondering if there are examples of using QMIX on PettingZoo environments. For QMIX, the key implementation detail seems to the [agent grouping](https://github.com/PettingZoo-Team/PettingZoo/issues/182); see also the [TwoStepGame example](https://github.com/ray-project/ray/blob/master/rllib/examples/two_step_game.py). However, the current PettingZoo environment in RLlib explicitly raises a `NotImplementedError` for the function `with_agent_groups`: 
https://github.com/ray-project/ray/blob/d80e08ce95e4e3943ab6bdcfa84455ed0377fa06/rllib/env/pettingzoo_env.py#L207 

Is there an existing pull request somewhere to implement `with_agent_groups` in RLlib, or is there some other way people use QMIX with PettingZoo environments?

I apologize for spamming the PettingZoo issues, especially because this more of an RLlib issue, but I thought this was more relevant for the widespread adoption of PettingZoo

**Comment by weepingwillowben** [comment]
Try using the `_GroupAgentsWrapper`

Something like this:
```
from ray.rllib.env.group_agents_wrapper import _GroupAgentsWrapper
groups = {"group_1": env.agents }
_GroupAgentsWrapper(PettingZooEnv(env), groups)
```

**Comment by rallen10** [comment]
@weepingwillowben Thanks! that worked! The only mod I had to make was to define `obs_space` and `act_space`. For a 2 floor prison environment with `vector_observation`, that looks like:

```
from gym.spaces import Box, Discrete, Tuple
from ray.rllib.env.group_agents_wrapper import _GroupAgentsWrapper
_GROUPED_OBSERVATION_SPACE = Tuple([
    Box(low=-300., high=300, shape=(1,)),
    Box(low=-300., high=300, shape=(1,)),
    Box(low=-300., high=300, shape=(1,)),
    Box(low=-300., high=300, shape=(1,))
])
_GROUPED_ACTION_SPACE = Tuple([
    Discrete(3),
    Discrete(3),
    Discrete(3),
    Discrete(3)
])

def prison_v1_env_creator(env_config):
    # create raw PettingZoo environment
    env = prison_v1.env(
        num_floors=_NUM_FLOORS,
        vector_observation=_VECTOR_OBSERVATION)

    # wrap env with RLlib-compatible PettingZooEnv
    env = PettingZooEnv(env)

    if env_config["grouped_agents"]:
        groups = {"group_1": env.agents }
        env = _GroupAgentsWrapper(env, groups, 
            obs_space = _GROUPED_OBSERVATION_SPACE,
            act_space = _GROUPED_ACTION_SPACE)

    return env
```
