### ISSUE TITLE
pursuit `train_pursuit` parameter

### ISSUE THREAD

**Issue by weepingwillowben** [PettingZoo-Team/PettingZoo#189]
It is not clear why someone would even want to train evaders to evade randomly moving pursuers. This seems like a very easy task that requires no coordination, defeating the entire purpose.

Also, right now there are a few issues with it: 

Setting the `train_pursuit` parameter to False in pursuit does change things in the base_pursuit.py. However, the agents are still named pursuer_0, etc, and there are only 8 of them instead of 20.

This is not ideal. Also need to investigate whether evader removal is implemented correctly.

**Comment by justinkterry** [comment]
fixed in 1.3.1
