### ISSUE TITLE
End-to-end working example?

### ISSUE THREAD

**Issue by carlos-aguayo** [PettingZoo-Team/PettingZoo#191]
Do you have an end to end working example with visualization?

After installing the library with pip, do you have working code that would train (even with random actions) a simple environment and then visualize it?

**Comment by justinkterry** [comment]
-Your usage of visualization here is not specific enough for anyone to know what you're asking for
-"train (even with random actions)" is nonsequiter
-You train a policy, not an environment?

You should read more about about RL, or whatever the topic is, before asking questions in a forum like this. ML projects of nontrivial size get crank inquiries all the time, they usually aren't replied to. If you have a conceptual question, try reddit.

I believe that if you look through the RLlib documentation you'll find what I assume you're looking for in terms of examples. This is a library of environments, not RL methods (RLlib has RL methods). If you're looking for general RL knowledge, try looking at OpenAI's booting up, or try playing with stable baselines.
