### ISSUE TITLE
SISL environments - ModuleNotFoundError: No module named 'Box2D'

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#194]
I am trying to use the multiwalker_v1 environment but getting a ModuleNotFoundError. To reproduce:

```bash
pip install pettingzoo[all]
```
Then in a python script or interpreter
```
from pettingzoo.sisl import multiwalker_v1
.
.
.
~/miniconda3/envs/pettingzoo_rllib/lib/python3.8/site-packages/pettingzoo/sisl/multiwalker/multiwalker_base.py in <module>
      4 from gym import spaces
      5 from gym.utils import seeding
----> 6 import Box2D
      7 from Box2D.b2 import (circleShape, contactListener, edgeShape, fixtureDef, polygonShape,
      8                       revoluteJointDef)

ModuleNotFoundError: No module named 'Box2D'
```

**Comment by rallen10** [comment]
Maybe this pull request is meant to fix this: https://github.com/PettingZoo-Team/PettingZoo/pull/193?

Is a new version (e.g. 1.3.1) planned to be released with this fix?

**Comment by justinkterry** [comment]
Ya we're going to release that tonight, along with some other fixes. We just found it ourselves. We're also changing CI to catch these things

**Comment by rallen10** [comment]
Sounds good! My temporary workaround is to simply install `gym[box2d]` which also requires you install `swig. Assuming the new release fixes this, I'll go ahead and close
