### ISSUE TITLE
Cannot understand how env.reset() works in MPE environments.

### ISSUE THREAD

**Issue by Kimonili** [PettingZoo-Team/PettingZoo#199]
Hi,

`env.reset()` returns an array of `Box(16,)` in multiagent scenarios. In the original version of the environment `env.reset()` would give a list of arrays, one for each agent and according to the observation space for each agent. For example, in the simple_tag environment the adversaries have an observation_space `Box(16,)` while the agent has `Box(14,)`. 

I also tried to pass the agent names inside the `env.reset()` function but all the returns were of size `Box(16,)`. 

So the question is: How to reset all the agents in the environment before the start of the training?

Maybe this is very basic, but I was used in the original version! Thank you in advance!

Update: I have a similar problem with the `env.step()` function as well. A feedback would be highly appreciated.

**Comment by weepingwillowben** [comment]
Thanks for updating the title. That makes your issue much more clear. 

If you want to use an API similar to the original MPE, I recommend using the [parallel api](https://www.pettingzoo.ml/api#parallel-api), where reset() returns dict of agent's observations and actions. You can create an environment that uses the parallel API with something like `simple_push_v0.parallel_env()`.

As for your question, in the AECenv API, the reset() method returns the observation of the first agent only. Then when you step the first agent, step(action) takes in the action of the first agent and returns the observation of the second agent, etc. The current agent is specified with `env.agent_selection`.

**Comment by Kimonili** [comment]
@weepingwillowben thank you for the quick reply!

So, if I understand correctly, AECenv API only supports serialized processing as the `step(action)` of `agent i` returns the observation of `agent i+1` (so there is no need to call `reset()` on the `agent i+1`?). On top of that, we can get the observation of `agent i` after completing one cicle (the `step(action)` function of the last agent returns the observation of the first agent?)   

But if `step(action)` of `agent i` only returns the observation of `agent i+1`, how do we get the reward, done and info?

**Comment by weepingwillowben** [comment]
For the first point, yes all of that is correct. 

For the second point, the `last()` method returns the reward, done and info for the current agent.

**Comment by weepingwillowben** [comment]
Please take a look at https://www.pettingzoo.ml/api before asking more questions. I will likely be able to answer many of them.

**Comment by weepingwillowben** [comment]
Of course, feel free to ask if the documentation is somehow not clear.

**Comment by Kimonili** [comment]
Thank you very much @weepingwillowben. 

I will look into it!
