### ISSUE TITLE
Does multiwalker only process/update a single agents observation in rllib pettingzoo_env.py?

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#205]
Sorry again for asking an rllib question in the pettingzoo repo.

I am trying to trace down exactly how observations are computed for each agent in multiwalker when using the pettingzoo_env.py wrapper in rllib. It seems as though only one agent's observation per cycle would be updated  in [pettingzoo_env.step](https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py#L163) and all others would be stale and incorrect. Starting from that step function in rllib and working "backward" to observation functions in petting zoo, I trace the following lines of code:
+ https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py#L180
+ https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/multiwalker/multiwalker.py#L69
+ https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/multiwalker/multiwalker_base.py#L465
+ https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/multiwalker/multiwalker_base.py#L449

This last line, which updates `self.last_obs[agent_id]`, only gets called if is_last is True. This is set here:

+ https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/multiwalker/multiwalker.py#L74
+ https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/utils/agent_selector.py#L22

But this makes it look like is_last is only True for the last agent in the cycle, which only occurs once in the [cycle of agents where step is called in pettingzoo_env.py](https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py#L163). All other agents which are not the last would then never have `self.last_obs[agent]` updated.

Therefore how are all the non-last agents' observations updated since `_agent_selector.is_last()` only returns True for one agent?

**Comment by weepingwillowben** [comment]
Can confirm that this is a real bug. 2 of the 3 walkers have identical observations for every time step. Good catch.

**Comment by weepingwillowben** [comment]
I'll fix and release this fix immidiately

**Comment by rallen10** [comment]
FYI I'm going to open a separate pull request that also pertains to multiwalker observations. See new issue here: https://github.com/PettingZoo-Team/PettingZoo/issues/206

**Comment by weepingwillowben** [comment]
This fix was released for pettingzoo==1.3.3
