### ISSUE TITLE
Multiwalker observations violate Box bounds due sampling normal distribution

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#206]
I believe I've come across a rare but inevitable bug with how multiwalker generates observations of neighboring walkers and the package. Since these observations are [drawn from normal distributions](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/multiwalker/multiwalker_base.py#L407) to introduce state uncertainty, there is a small chance the sample will fall on the extreme tail of the distribution and [violate the observation space Box bounds](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/multiwalker/multiwalker_base.py#L244). With long enough training experiments, you will eventually encounter this rare occurrence.

Quick fix would simply be to clip the observations to the bounds.

**Comment by justinkterry** [comment]
-I'll discuss this more with Ben, but it seems to me like the better solution would be to clip the noise and not the entire reward
-This appears to be an upstream bug in the Gym environment this is based on?

**Comment by rallen10** [comment]
Maybe we're talking about different things because I'm not proposing doing anything to the reward. I think I see what your are saying, though: only clip the observation elements that are drawn from distributions, not every element in the observation vector. That seems reasonable. 

Perhaps this problem goes beyond just the elements that are drawn from a normal distribution, though. Specifically, the observation space bounds are based on a lidar range metric, however there are observation components that have nothing to do with range (e.g. package angle). Perhaps a more robust solution would be to use arrays to define [the bounds of the observation space](https://github.com/PettingZoo-Team/PettingZoo/blob/83b82f3dd8f435e4d975752db1b42fc948411ff6/pettingzoo/sisl/multiwalker/multiwalker_base.py#L244), tailoring it to each individual element, instead of a single scalar for all elements.

**Comment by justinkterry** [comment]
Reward was a typo, my apologies. I'll talk about the other part with Ben

**Comment by weepingwillowben** [comment]
I am looking at the observation space, and this space should definitely be an array rather than a scalar. I am uncomfortable clipping observations unless it is clear what exactly is being clipped. One problem I see is that the relative position observations are effectively unbounded, so if one walker just starts running away from the others somehow, this distance can get quite large.

**Comment by justinkterry** [comment]
Me and Ben talked it over. The problem appears to be that we need a vector observation space, and it's not clear what the bounds on certain elements are, and there's other elements that probably should be fixed. The long term solution to this is to fix this, but this will be fairly time consuming--it'll probably have to wait till after AAMAS, possibly a bit longer.

Given this, I'd rather keep this issue open and not merge a clipping fix. You can just apply your fix with a supersuit wrapper for now though, Ben will reply to this with the relevant code snippet

**Comment by justinkterry** [comment]
What happened here is in Gym, where this happens from, the observation is -inf to inf. When Jayesh Gupta and his people did this environment, they kept that. When we added it to PettingZoo, Mario was put in charge of figuring out a real action space so things like normalization could work, for this and waterworld. That wasn't done correctly, so no we're here. We're going to upstream this fix to Gym's box2d walker once we sort it out though.

**Comment by weepingwillowben** [comment]
As a workaround while this gets worked out more permanently, you can use supersuit's observation lambda wrapper to clip the observations like so:

```
space = env.observation_spaces[env.agents[0]]
env = supersuit.observation_lambda_v0(env, lambda obs: np.clip(obs, space.low, space.high))
```

**Comment by rallen10** [comment]
Great! Thanks for the workaround. I'll go ahead an close my pull request unmerged

**Comment by justinkterry** [comment]
So we investigated this in a lot more detail, and it turns out that a finite observation space is a really bad idea. PR #277 makes the action space infinite again.
