### ISSUE TITLE
Error with Tiger-Deer Env: Selecting Invalid Agent.

### ISSUE THREAD

**Issue by jdpena** [PettingZoo-Team/PettingZoo#209]
Hi,

I've been running the MAgent Tiger-Deer environment with 2 different algorithms: a [RandomLearner](https://chuacheowhuan.github.io/RLlib_rand_policy/) and `rllib`'s PPO. I'm also currently using `rllib`'s [PettingZooEnv](https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py). It seems both of the algorithms work for some number of iterations, but then error-out in this line https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py#L161. 

The issue is that the agent being selected, `deer_92`, is not in the `action_dict`. I checked the `self.aec_env.dones` dict, however, and the agent is there. I added a snippet of the output, below. I printed out relevant info (shown after each `== start step ==`) when entering the [step()](https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py#L141) function.  Furthermore, it also appears all steps prior to this error only select `deer_0` as the agent. I've re-ran the experiment several times and it always has the same result (e.g., `deer_0` is always chosen and then it errors-out once any other agent is chosen).

I'm not sure if this is an issue with rllib, the Tiger-Deer env, or my own config.

```
[2m[36m(pid=34152)[0m =============== start step =====================
[2m[36m(pid=34152)[0m self.aec_env.agent_selection --> deer_0
[2m[36m(pid=34152)[0m stepped_agents --> set()
[2m[36m(pid=34152)[0m list(action_dict) --> ['deer_0', 'deer_1', 'deer_2', 'deer_3', 'deer_4', 'deer_5', 'deer_6', 'deer_7', 'deer_8', 'deer_9', 'deer_10', 'deer_11', 'deer_12', 'deer_13', 'deer_14', 'deer_15', 'deer_16', 'deer_17', 'deer_18', 'deer_19', 'deer_20', 'deer_21', 'deer_22', 'deer_23', 'deer_24', 'deer_25', 'deer_26', 'deer_27', 'deer_28', 'deer_29', 'deer_30', 'deer_31', 'deer_32', 'deer_33', 'deer_34', 'deer_35', 'deer_36', 'deer_37', 'deer_38', 'deer_39', 'deer_40', 'deer_41', 'deer_42', 'deer_43', 'deer_44', 'deer_45', 'deer_46', 'deer_47', 'deer_48', 'deer_49', 'deer_50', 'deer_51', 'deer_52', 'deer_53', 'deer_54', 'deer_55', 'deer_56', 'deer_57', 'deer_58', 'deer_59', 'deer_60', 'deer_61', 'deer_62', 'deer_63', 'deer_64', 'deer_65', 'deer_66', 'deer_67', 'deer_68', 'deer_69', 'deer_70', 'deer_71', 'deer_72', 'deer_73', 'deer_74', 'deer_75', 'deer_76', 'deer_77', 'deer_78', 'deer_79', 'deer_80', 'deer_81', 'deer_82', 'deer_83', 'deer_84', 'deer_85', 'deer_86', 'deer_87', 'deer_88', 'deer_89', 'deer_90', 'deer_91', 'deer_92', 'deer_93', 'deer_94', 'deer_95', 'deer_96', 'deer_97', 'deer_98', 'deer_99', 'deer_100', 'tiger_0', 'tiger_1', 'tiger_2', 'tiger_3', 'tiger_4', 'tiger_5', 'tiger_6', 'tiger_7', 'tiger_8', 'tiger_9', 'tiger_10', 'tiger_11', 'tiger_12', 'tiger_13', 'tiger_14', 'tiger_15', 'tiger_16', 'tiger_17', 'tiger_18', 'tiger_19']
[2m[36m(pid=34152)[0m agent in action_dict -->  True
[2m[36m(pid=34152)[0m agent in self.aec_env.dones --> False
[2m[36m(pid=34152)[0m =============== start step =====================
[2m[36m(pid=34152)[0m self.aec_env.agent_selection --> deer_0
[2m[36m(pid=34152)[0m stepped_agents --> set()
[2m[36m(pid=34152)[0m list(action_dict) --> ['deer_0', 'deer_1', 'deer_2', 'deer_3', 'deer_4', 'deer_5', 'deer_6', 'deer_7', 'deer_8', 'deer_9', 'deer_10', 'deer_11', 'deer_12', 'deer_13', 'deer_14', 'deer_15', 'deer_16', 'deer_17', 'deer_18', 'deer_19', 'deer_20', 'deer_21', 'deer_22', 'deer_23', 'deer_24', 'deer_25', 'deer_26', 'deer_27', 'deer_28', 'deer_29', 'deer_30', 'deer_31', 'deer_32', 'deer_33', 'deer_34', 'deer_35', 'deer_36', 'deer_37', 'deer_38', 'deer_39', 'deer_40', 'deer_41', 'deer_42', 'deer_43', 'deer_44', 'deer_45', 'deer_46', 'deer_47', 'deer_48', 'deer_49', 'deer_50', 'deer_51', 'deer_52', 'deer_53', 'deer_54', 'deer_55', 'deer_56', 'deer_57', 'deer_58', 'deer_59', 'deer_60', 'deer_61', 'deer_62', 'deer_63', 'deer_64', 'deer_65', 'deer_66', 'deer_67', 'deer_68', 'deer_69', 'deer_70', 'deer_71', 'deer_72', 'deer_73', 'deer_74', 'deer_75', 'deer_76', 'deer_77', 'deer_78', 'deer_79', 'deer_80', 'deer_81', 'deer_82', 'deer_83', 'deer_84', 'deer_85', 'deer_86', 'deer_87', 'deer_88', 'deer_89', 'deer_90', 'deer_91', 'deer_92', 'deer_93', 'deer_94', 'deer_95', 'deer_96', 'deer_97', 'deer_98', 'deer_99', 'deer_100', 'tiger_0', 'tiger_1', 'tiger_2', 'tiger_3', 'tiger_4', 'tiger_5', 'tiger_6', 'tiger_7', 'tiger_8', 'tiger_9', 'tiger_10', 'tiger_11', 'tiger_12', 'tiger_13', 'tiger_14', 'tiger_15', 'tiger_16', 'tiger_17', 'tiger_18', 'tiger_19']
[2m[36m(pid=34152)[0m agent in action_dict -->  True
[2m[36m(pid=34152)[0m agent in self.aec_env.dones -->  False
[2m[36m(pid=34152)[0m =============== start step =====================
[2m[36m(pid=34152)[0m self.aec_env.agent_selection --> deer_92
[2m[36m(pid=34152)[0m stepped_agents --> set()
[2m[36m(pid=34152)[0m list(action_dict) --> ['deer_0', 'deer_1', 'deer_2', 'deer_3', 'deer_4', 'deer_5', 'deer_6', 'deer_7', 'deer_8', 'deer_9', 'deer_10', 'deer_11', 'deer_12', 'deer_13', 'deer_14', 'deer_15', 'deer_16', 'deer_17', 'deer_18', 'deer_19', 'deer_20', 'deer_21', 'deer_22', 'deer_23', 'deer_24', 'deer_25', 'deer_26', 'deer_27', 'deer_28', 'deer_29', 'deer_30', 'deer_31', 'deer_32', 'deer_33', 'deer_34', 'deer_35', 'deer_36', 'deer_37', 'deer_38', 'deer_39', 'deer_40', 'deer_41', 'deer_42', 'deer_43', 'deer_44', 'deer_45', 'deer_46', 'deer_47', 'deer_48', 'deer_49', 'deer_50', 'deer_51', 'deer_52', 'deer_53', 'deer_54', 'deer_55', 'deer_56', 'deer_57', 'deer_58', 'deer_59', 'deer_60', 'deer_61', 'deer_62', 'deer_63', 'deer_64', 'deer_65', 'deer_66', 'deer_67', 'deer_68', 'deer_69', 'deer_70', 'deer_71', 'deer_72', 'deer_73', 'deer_74', 'deer_75', 'deer_76', 'deer_77', 'deer_78', 'deer_79', 'deer_80', 'deer_81', 'deer_82', 'deer_83', 'deer_84', 'deer_85', 'deer_86', 'deer_87', 'deer_88', 'deer_89', 'deer_90', 'deer_91', 'deer_93', 'deer_94', 'deer_95', 'deer_96', 'deer_97', 'deer_98', 'deer_99', 'deer_100', 'tiger_0', 'tiger_1', 'tiger_2', 'tiger_3', 'tiger_4', 'tiger_5', 'tiger_6', 'tiger_7', 'tiger_8', 'tiger_9', 'tiger_10', 'tiger_11', 'tiger_12', 'tiger_13', 'tiger_14', 'tiger_15', 'tiger_16', 'tiger_17', 'tiger_18', 'tiger_19']
[2m[36m(pid=34152)[0m agent in action_dict -->  False
[2m[36m(pid=34152)[0m agent in self.aec_env.dones -->  True
== Status ==
Memory usage on this node: 24.8/377.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/80 CPUs, 0/2 GPUs, 0.0/252.88 GiB heap, 0.0/77.54 GiB objects (0/1.0 GPUType:V100)
Result logdir: /home/ray_results/Campaign_Tiger-Deer-v1
Number of trials: 1 (1 ERROR)
+------------------------------------------+----------+-------+--------+------------------+------+----------+
| Trial name                               | status   | loc   |   iter |   total time (s) |   ts |   reward |
|------------------------------------------+----------+-------+--------+------------------+------+----------|
| PS_PPO_Trainer_Tiger-Deer-v1_41b65_00000 | ERROR    |       |      3 |          3576.35 | 3672 | 0.166667 |
+------------------------------------------+----------+-------+--------+------------------+------+----------+
Number of errored trials: 1
```

If I use the `PettingZooEnv` in version in `ray==0.87`, the error is https://github.com/ray-project/ray/blob/releases/0.8.7/rllib/env/pettingzoo_env.py#L165. 

Lastly, I also applied the following `SuperSuit` wrappers: `pad_observations_v0`, `pad_action_space_v0`, `agent_indicator_v0`, and `flatten_v0`, and I'm running `PettingZoo==1.3.3` and `SuperSuit==2.1.0`.

Thanks.

**Comment by weepingwillowben** [comment]
Hi, thanks for your interest in our library and for the detailed bug report.

Unfortunately, the PettingZooEnv in that version of ray had a bug which causes the error you see. We fixed the bug and replaced it recently, so it is only available in the nightly build of ray (1.1.0.dev). If you do not wish to deal with nightly builds, then you can just copy the PettingzooEnv into your code from https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py. This class will work with prior versions of rllib.

**Comment by jdpena** [comment]
Hi Ben,

Thanks for the quick response. I should have been more clear (rather than just linking to the code), but the version of `PettingZooEnv` that I am currently using is the same one you just pointed me to - the one from [ray v1.1.0](https://docs.ray.io/en/master/_modules/ray/rllib/env/pettingzoo_env.html). Thus, the error I am receiving is coming from using the updated `PettingZooEnv`, stemming from https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py#L161.

**Comment by weepingwillowben** [comment]
I have a PR for ray with fixes this issue https://github.com/ray-project/ray/pull/11060

**Comment by weepingwillowben** [comment]
Can I ask what you are using Tiger-deer for?

For context, right now, we have plans to change the reward structure of certain MAgent environments (especially tiger-deer and gather) to make them more ecologically reasonable so that they are suitable for study of emergent behavior. Right now, the behavior described for gather in the MAgent paper seems like a trivial weighing of the two primary rewards in the environment: https://www.pettingzoo.ml/magent/gather, which seems deeply uninteresting to us.

We also plan to change the default setting of the battle environments to not contain the global minimap (and instead offer this as an optional parameter). This will mean that by default, agent communication will be required for large scale coordination, making the environments much more realistic and challenging.

Thoughts?

**Comment by rallen10** [comment]
A key interest of tiger-deer, and other MAgent envs, is the concept of health and agent attrition. Almost all real-world/physical multi-agent systems and many multi-agent video games have some form of agent health and/or agent attrition, yet there are few MARL learning environments that capture this property. Tiger-deer is one of those. Changing the reward weighting scheme (i.e. "payoff function" from game theory) to make it more interesting sounds like a good idea, as long as it doesn't remove this element of health/attrition.

To generalize a bit beyond health and agent attrition, I think it is important to develop new environments that have a __variable number of agents__ within an episode and across different episodes. This generalizes on the idea of agent attrition because it could also incorporate agent generation during an episode.

**Comment by weepingwillowben** [comment]
The problem with tiger-deer is that the tiger can damage the deer by itself, and it gets increased longevity when killing the deer, but it is only rewarded when attacking with another tiger. https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/magent/tiger_deer_v1.py#L51 This combination is really quite strange. Gather has similarly strange reward/healing combinations.

I copied these settings from the original MAgent codebase without significant alteration, and was planning on seeing if there is something more reasonable. Perhaps making a deer heal so quickly that only by two tigers cooperating can they actually accomplish anything? And making the primary reward based on deer death rather than attack, with a small shaping reward for attacking?

Thoughts?

**Comment by rallen10** [comment]
At risk of stretching the biology/ecology analogy too far, what about "lion-elephant" and/or "bees-vs-hornets"

__Lion-Elephant:__ Similar to tiger-deer, now with lions hunting elephants, but the difference being that a single lion can't harm an elephant by itself. The lion can only gain longevity by attacking an elephant with at least N other lions. Then have reward more directly correlated with longevity instead of the disconnect you described with tiger-deer. In fact, you could make the reward structure even more interesting, and coordination even more necessary, if the lions lose health if they attack an elephant without the sufficient number of other lions For inspiration [see this BBC clip (warning: it's lions hunting an elephant)](https://www.youtube.com/watch?v=PziDIb5_Qys&feature=youtu.be&t=330)

__Bees-vs-Hornets:__ This environment would flip the script a bit. Hornets hunt bees and a single hornet can easily kill a bee and gain longevity. However if enough bees attack a hornet at the same time, they can overpower it and kill it. The reward structure would be a zero-sum game: every bee that dies is a reward for hornets, and every hornet that dies is a reward for bees (with some appropriate weighting to make the game well balanced). For inspiration [see this other  BBC wildlife documentary clip](https://www.youtube.com/watch?v=UNroEwFxh6I&feature=youtu.be&t=185)

**Comment by jdpena** [comment]
@weepingwillowben the updated PettingZooEnv in your ray PR fixed my issues. As for the Tiger-Deer env, I think your proposed changes to the reward sound very reasonable. I also think the Lion-Elephant and Bees-vs-Hornets are interesting takes on the envs.

I'll close the PR for now and will let you know of any other issues.

Thanks again!

**Comment by jdpena** [comment]
@weepingwillowben I ran into an error using the [ray-project/ray#11060](https://github.com/ray-project/ray/pull/11060) fix, specifically, [pettingzoo_env.py#L162](https://github.com/ray-project/ray/blob/bb4f42741b18dcb827ca7cb49473d2c55b5f4d41/rllib/env/pettingzoo_env.py#L162). The issue is that `None` is being passed into the `step()` function, but I believe it should be `agent` (I'm in the process of testing this out).  I added the full stack trace below.

Shall I re-open this issue, open a new one, or just leave it closed?

```
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 398, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/home/documents/pettingzoo-rllib/utils/pettingzoo_env.py", line 169, in step
    self.aec_env.step(None)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/base_aec_wrapper.py", line 59, in step
    next_obs = super().step(action, observe=observe)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/pettingzoo/utils/wrappers.py", line 102, in step
    super().step(action, False)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    next_obs = self.env.step(action, observe=observe)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/base_aec_wrapper.py", line 59, in step
    next_obs = super().step(action, observe=observe)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/pettingzoo/utils/wrappers.py", line 102, in step
    super().step(action, False)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    next_obs = self.env.step(action, observe=observe)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/base_aec_wrapper.py", line 58, in step
    action = self._modify_action(agent, action)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/aec_wrappers.py", line 307, in _modify_action
    new_action = homogenize_ops.dehomogenize_actions(self.env.action_spaces[agent], action)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/action_transforms/homogenize_ops.py", line 65, in dehomogenize_actions
    if action > n - 1:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by weepingwillowben** [comment]
Put a fix here: #214 

I'll get this released asap, and get back to you.

**Comment by weepingwillowben** [comment]
Actually, there is some complexity involved in this fix that I don't have the space to deal with this week. Sorry.

As a workaround, note that there is a ParallelPettingZooEnv in https://github.com/ray-project/ray/blob/bb4f42741b18dcb827ca7cb49473d2c55b5f4d41/rllib/env/pettingzoo_env.py

You can create a parallel env with tiger_deer_v0.parallel_env(), and use supersuit exactly as before, just wrapping with the ParallelPettingZooEnv before using with rllib.

Parallel API is documented here: https://www.pettingzoo.ml/api#parallel-api

**Comment by jdpena** [comment]
@weepingwillowben thanks for all your support thus far. Unfortunately, it appears the `ParallelPettingZooEnv` suffers from the same issue where a selected agent is not in the `actions_dict` but rather in the `self.aec_env.dones`. This time the error is thrown from [pettingzoo/utils/to_parallel.py#L39](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/utils/to_parallel.py#L39). I added the error below and the values which caused the crash.

Error:
```
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 569, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 398, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/home/documents/pettingzoo-rllib/utils/zoo_wrapper.py", line 261, in step
    aobs, arew, adones, ainfo = self.par_env.step(action_dict)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/pettingzoo/utils/to_parallel.py", line 53, in step
    ), "Live environment agent is not in actions dictionary"
AssertionError: Live environment agent is not in actions dictionary
```
Output values (Note `deer_0` missing from `actions_dict` but present in `aec_env.dones`):
```
agent --> deer_0
actions_dict --> {'deer_1': 1, 'deer_2': 0, 'deer_3': 1, 'deer_4': 3, 'deer_5': 5, 'deer_6': 3, 'deer_7': 3, 'deer_8': 4, 'deer_9': 1, 'deer_10': 0, 'deer_11': 4, 'deer_12': 4, 'deer_13': 4, 'deer_14': 7, 'deer_15': 4, 'deer_16': 6, 'deer_17': 8, 'deer_18': 6, 'deer_19': 4, 'deer_20': 5, 'deer_21': 2, 'deer_22': 5, 'deer_23': 4, 'deer_24': 1, 'deer_25': 1, 'deer_26': 3, 'deer_27': 5, 'deer_28': 4, 'deer_29': 0, 'deer_30': 5, 'deer_31': 5, 'deer_32': 4, 'deer_33': 3, 'deer_34': 0, 'deer_35': 8, 'deer_36': 7, 'deer_37': 7, 'deer_38': 7, 'deer_39': 2, 'deer_40': 4, 'deer_41': 2, 'deer_42': 8, 'deer_43': 8, 'deer_44': 0, 'deer_45': 7, 'deer_46': 0, 'deer_47': 4, 'deer_48': 8, 'deer_49': 4, 'deer_50': 7, 'deer_51': 7, 'deer_52': 6, 'deer_53': 8, 'deer_54': 6, 'deer_55': 7, 'deer_56': 7, 'deer_57': 8, 'deer_58': 4, 'deer_59': 2, 'deer_60': 2, 'deer_61': 2, 'deer_62': 4, 'deer_63': 7, 'deer_64': 8, 'deer_65': 4, 'deer_66': 7, 'deer_67': 0, 'deer_68': 1, 'deer_69': 6, 'deer_70': 4, 'deer_71': 0, 'deer_72': 2, 'deer_73': 4, 'deer_74': 7, 'deer_75': 4, 'deer_76': 1, 'deer_77': 2, 'deer_78': 7, 'deer_79': 7, 'deer_80': 5, 'deer_81': 0, 'deer_82': 6, 'deer_83': 2, 'deer_84': 6, 'deer_85': 1, 'deer_86': 0, 'deer_87': 7, 'deer_88': 8, 'deer_89': 3, 'deer_90': 3, 'deer_91': 4, 'deer_92': 3, 'deer_93': 8, 'deer_94': 5, 'deer_95': 4, 'deer_96': 1, 'deer_97': 8, 'deer_98': 4, 'deer_99': 7, 'deer_100': 2, 'tiger_0': 3, 'tiger_1': 4, 'tiger_2': 0, 'tiger_3': 3, 'tiger_4': 5, 'tiger_5': 5, 'tiger_6': 5, 'tiger_7': 5, 'tiger_8': 7, 'tiger_9': 1, 'tiger_10': 3, 'tiger_11': 4, 'tiger_12': 3, 'tiger_13': 3, 'tiger_14': 1, 'tiger_15': 3, 'tiger_16': 1, 'tiger_17': 1, 'tiger_18': 1, 'tiger_19': 0}
aec_env.dones --> {'deer_0': True, 'deer_1': False, 'deer_2': False, 'deer_3': False, 'deer_4': False, 'deer_5': False, 'deer_6': False, 'deer_7': False, 'deer_8': False, 'deer_9': False, 'deer_10': False, 'deer_11': False, 'deer_12': False, 'deer_13': False, 'deer_14': False, 'deer_15': False, 'deer_16': False, 'deer_17': False, 'deer_18': False, 'deer_19': False, 'deer_20': False, 'deer_21': False, 'deer_22': False, 'deer_23': False, 'deer_24': False, 'deer_25': False, 'deer_26': False, 'deer_27': False, 'deer_28': False, 'deer_29': False, 'deer_30': False, 'deer_31': False, 'deer_32': False, 'deer_33': False, 'deer_34': False, 'deer_35': False, 'deer_36': False, 'deer_37': False, 'deer_38': False, 'deer_39': False, 'deer_40': False, 'deer_41': False, 'deer_42': False, 'deer_43': False, 'deer_44': False, 'deer_45': False, 'deer_46': False, 'deer_47': False, 'deer_48': False, 'deer_49': False, 'deer_50': False, 'deer_51': False, 'deer_52': False, 'deer_53': False, 'deer_54': False, 'deer_55': False, 'deer_56': False, 'deer_57': False, 'deer_58': False, 'deer_59': False, 'deer_60': False, 'deer_61': False, 'deer_62': False, 'deer_63': False, 'deer_64': False, 'deer_65': False, 'deer_66': False, 'deer_67': False, 'deer_68': False, 'deer_69': False, 'deer_70': False, 'deer_71': False, 'deer_72': False, 'deer_73': False, 'deer_74': False, 'deer_75': False, 'deer_76': False, 'deer_77': False, 'deer_78': False, 'deer_79': False, 'deer_80': False, 'deer_81': False, 'deer_82': False, 'deer_83': False, 'deer_84': False, 'deer_85': False, 'deer_86': False, 'deer_87': False, 'deer_88': False, 'deer_89': False, 'deer_90': False, 'deer_91': False, 'deer_92': False, 'deer_93': False, 'deer_94': False, 'deer_95': False, 'deer_96': False, 'deer_97': False, 'deer_98': False, 'deer_99': False, 'deer_100': False, 'tiger_0': False, 'tiger_1': False, 'tiger_2': False, 'tiger_3': False, 'tiger_4': False, 'tiger_5': False, 'tiger_6': False, 'tiger_7': False, 'tiger_8': False, 'tiger_9': False, 'tiger_10': False, 'tiger_11': False, 'tiger_12': False, 'tiger_13': False, 'tiger_14': False, 'tiger_15': False, 'tiger_16': False, 'tiger_17': False, 'tiger_18': False, 'tiger_19': False}
```

Thanks again for all your help with this issue.

**Comment by weepingwillowben** [comment]
We just discovered this error internally as well. I am really sorry about these continued errors, the handling of agent death is just really tricky due to the differences between pettingzoo's and RLLib's APIs. 

Thanks for your example, it is helpful to know that it is likely the first agent dying that is causing the problem.

**Comment by jdpena** [comment]
I found another issue, which may be part of the same problem, Rllib, or my understanding of the Tiger-Deer env:

The padded action space and observation space are `Discrete(9)` and `Box(9, 9, 25)`, respectively. When I flatten the observation space, I get `Box(2025,)`. When I run through Rllib, though, I receive an assertion error because the observation spaces are not equal. The dimensions that Rllib receives are `(9,9,146)` and `(11826,)` for the flattened case. The error is being thrown from [rllib/models/preprocessors.py#L60](https://github.com/ray-project/ray/blob/releases/1.0.0/rllib/models/preprocessors.py#L60) calling [gym/spaces/box.py#L125](https://github.com/openai/gym/blob/master/gym/spaces/box.py#L125). I added a truncated stack trace below for the flattened case, where it expects a numpy array of size `(2025,)` but received one with shape `(11826,)`. 

I had caught this error early on and simply hardcoded the adjusted observations in my Rllib policies, but a recent code refactor my team did brought this issue back up.

```
ray.exceptions.RayTaskError(ValueError): [36mray::RolloutWorker.par_iter_next()[39m (pid=26611, ip=10.2.0.228)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/util/iter.py", line 1152, in par_iter_next
    return next(self.local_it)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 288, in gen_rollouts
    yield self.sample()
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 579, in sample
    batches = [self.input_reader.next()]
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 93, in next
    batches = [self.get_data()]
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 209, in get_data
    item = next(self.rollout_provider)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 604, in _env_runner
    perf_stats=perf_stats,
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 798, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 165, in transform
    self.check_shape(observation)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 63, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', Box(2025,), array([0., 0., 0., ..., 0., 0., 0.], dtype=float32))
```

**Comment by weepingwillowben** [comment]
This is definitely a different issue. Making a new issue with it here #218

**Comment by weepingwillowben** [comment]
As for the original issue, here are my thoughts:

The assert you are hitting is:

```
assert agent in actions or self.aec_env.dones[agent], \
     "Live environment agent is not in actions dictionary"
```

But you claim that `aec_env.dones["deer_0"] is true. So the assertion shouldn't possibly run.

Then I noticed that the commit that changed that line of code was done after the last release. 

I'll release this change and then hopefully you can simply update your version of pettingzoo, and things will work.

**Comment by weepingwillowben** [comment]
Ok, pettingzoo==1.3.4 has been released. Hopefully this fixes your issue. If not, please let me know.

**Comment by jdpena** [comment]
Thanks! I just finished testing and it still fails, this time caused [L33](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/utils/to_parallel.py). The stack trace is below -- the issue being that action `None` is passed from L33 and crashing in `supersuit` when padding the action space. (Note that this is the same error I had mentioned earlier ([209#issuecomment-701044797](https://github.com/PettingZoo-Team/PettingZoo/issues/209#issuecomment-701044797)), but using `ParallelPettingZooEnv` rather than `PettingZooEnv` ).

```
  File "/home/documents/PettingZoo/pettingzoo/utils/to_parallel.py", line 33, in step
    self.aec_env.step(None)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/base_aec_wrapper.py", line 59, in step
    next_obs = super().step(action, observe=observe)
  File "/home/documents/PettingZoo/pettingzoo/utils/wrappers.py", line 102, in step
    super().step(action, False)
  File "/home/documents/PettingZoo/pettingzoo/utils/wrappers.py", line 63, in step
    next_obs = self.env.step(action, observe=observe)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/base_aec_wrapper.py", line 59, in step
    next_obs = super().step(action, observe=observe)
  File "/home/documents/PettingZoo/pettingzoo/utils/wrappers.py", line 102, in step
    super().step(action, False)
  File "/home/documents/PettingZoo/pettingzoo/utils/wrappers.py", line 63, in step
    next_obs = self.env.step(action, observe=observe)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/base_aec_wrapper.py", line 58, in step
    action = self._modify_action(agent, action)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/aec_wrappers.py", line 307, in _modify_action
    new_action = homogenize_ops.dehomogenize_actions(self.env.action_spaces[agent], action)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/supersuit/action_transforms/homogenize_ops.py", line 65, in dehomogenize_actions
    if action > n - 1:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

Just so that I understand the changes in `to_parallel.py`:

- First, commit [8567d9f](https://github.com/PettingZoo-Team/PettingZoo/commit/8567d9fe762fe263e38df6214b9647dd51f09f25) changed `actions[agent]` --> `actions.get(agent,None)` in [L33](https://github.com/PettingZoo-Team/PettingZoo/blob/8567d9fe762fe263e38df6214b9647dd51f09f25/pettingzoo/utils/to_parallel.py#L33) and [L41](https://github.com/PettingZoo-Team/PettingZoo/blob/8567d9fe762fe263e38df6214b9647dd51f09f25/pettingzoo/utils/to_parallel.py#L41).

- Then, commit [120bcb9](https://github.com/PettingZoo-Team/PettingZoo/commit/120bcb9151f1502d501cdb86e5765896070f0590#diff-110f9f4f94e8b250806a2c9f27051fe3) changed `actions.get(agent,None)` --> `None` in [L33](https://github.com/PettingZoo-Team/PettingZoo/blob/120bcb9151f1502d501cdb86e5765896070f0590/pettingzoo/utils/to_parallel.py#L33) and `actions[agent]` in [L41](https://github.com/PettingZoo-Team/PettingZoo/blob/120bcb9151f1502d501cdb86e5765896070f0590/pettingzoo/utils/to_parallel.py#L41).

- Lastly, commit [712b757](https://github.com/PettingZoo-Team/PettingZoo/blob/712b7574075059a96668f5149f1234733d8c4f61/pettingzoo/utils/to_parallel.py) reverts [L41](https://github.com/PettingZoo-Team/PettingZoo/blob/712b7574075059a96668f5149f1234733d8c4f61/pettingzoo/utils/to_parallel.py#L41) to `actions.get(agent, None)`, but leaves [L33](https://github.com/PettingZoo-Team/PettingZoo/blob/712b7574075059a96668f5149f1234733d8c4f61/pettingzoo/utils/to_parallel.py#L33) intact. 

I'm wondering if L33 also needs to be reverted. I'll make the change locally and test again.

**Comment by weepingwillowben** [comment]
I am very sorry about the continued failures here. The plan is to go through and refactor all of this shit over the next week or two, possibly extend the API to better support parallel actions, and remove all these weird complex loops.

**Comment by jdpena** [comment]
I re-ran some code I had for several magent envs and I'm no longer receiving agent death issues. My implementation of parameter shared PPO doesn't show any agents learning anything, however, whereas before they would learn until the agent death problems. I'll check to see if there's another bug, though it may be my own code. 

In any case, the agent death problems seem fixed to me. I'll open a separate issue if needed.
