### ISSUE TITLE
[rllib] PettingZoo's No-limit Texas Holdem environment compatibility

### ISSUE THREAD

**Issue by DoxakisCh** [PettingZoo-Team/PettingZoo#211]
Hello,

I am trying to use rllib's algorithms on PettingZoo's No-limit Texas Holdem environment. From what I understand in rllib's documentation, there is a PettingZooEnv class in order to make these environments compatible with rllib. But this class can be used only for agents that act simultaneously, and not for turn-based games like Poker or Chess, which fall under the classic category of PettingZoo's environments. Additionally, these games have also illegal moves that alter the action space in each step.

Therefore, is there any solution to this problem? Any workaround that would prove useful to this compatibility problem? Alternatively, is there any other library with the particular environment (No-limit Texas Holdem) that I could use instead with rllib?

The same issue was posted on ray's repo: https://github.com/ray-project/ray/issues/11072

Thank you in advance.

**Comment by weepingwillowben** [comment]
I guess RLLIB's MultiAgentEnv is expressive enough to support turned based games. However, there is no explicit support for that right now in the PettingZooEnv. I can look into adding support for this in a few weeks if you think this is valuable. 

However, there remains the problem that I do not know how to make rllib policies only select legal moves. That makes the classic environments very hard to train with rllib.

**Comment by weepingwillowben** [comment]
It looks like there is a documented way of doing action masking (refusing to take illegal actions) here: https://docs.ray.io/en/master/rllib-models.html#variable-length-parametric-action-spaces

**Comment by DoxakisCh** [comment]
Thank you for your quick response. I will take your helpful comments into consideration and try to implement a new class for No-limit Texas Holdem environment. Nevertheless, I think that adding support for the whole classic category of environments in rllib is very useful.

**Comment by weepingwillowben** [comment]
Yes, we will keep this issue open with that in consideration.

**Comment by justinkterry** [comment]
So this should fixed in full with the new pettingzoo 1.4.0 release and this pr: https://github.com/ray-project/ray/pull/11873

Let us know if you have any problems
