### ISSUE TITLE
Is there a single player version of Atari?

### ISSUE THREAD

**Issue by Ann-eat-apple** [PettingZoo-Team/PettingZoo#213]
Can I instantiate a single player version of Atari with PettingZoo?

Looks like

```
from pettingzoo.atari import pong_classic_v0
pong_classic_v0.env() 
```

it is still a multiplayer version.

Nope, I can't do `gym.make('Pong-v0')` because PettingZoo has 18 actions while the gym version only got 6.

**Comment by justinkterry** [comment]
PettingZoo is a multiplayer library. We don't support single player games (except MPE simple speaker since it was part of the entire set). Pong is an inherently multiplayer game. Gym includes a single player mode of the game. We don't include though, though in principle our API does support it.

**Comment by Ann-eat-apple** [comment]
Yes, I just want to train against a computer-policy. For the Pong, do you have the hand-coded policy?

**Comment by weepingwillowben** [comment]
If you want to make a pettingzoo Pong environment with a Discrete(6) action space like gym, you can do:

```
pong_classic_v0.env(full_action_space=False)
```
