### ISSUE TITLE
Enabling MAgent map_size as a Parameter

### ISSUE THREAD

**Issue by jdpena** [PettingZoo-Team/PettingZoo#223]
I see that `map_size` is fixed for each MAgent environment, even though it can be passed into the underlying game environment. Could this be added as an input parameter to the magent env wrappers or does the remainder of the env setup (e.g., number of agents) depend on a fixed size?

**Comment by justinkterry** [comment]
This is something we're planning to add as part of the overhaul of Magent we've been planning to do for the past month or so; we hopefully can do it in the next 3 weeks. Is this specific option something you guys need for AAMAS?

**Comment by yutaizhou** [comment]
@justinkterry It would be VERY nice for us to get that for AAMAS, but I don't think it's **absolutely** crucial. 

With that being said, If you can answer the [last question](https://github.com/PettingZoo-Team/PettingZoo/issues/222) I posted here, that would help  a lot!

**Comment by weepingwillowben** [comment]
The remainder of the env setup does depend on the map size. Some environments, like battle, used to allow for different map sizes, and adjusted the number of agents to the map size. But this only worked for certain map sizes, and if the size was too small (even 25 is too small), it just crashed, as it added agents to parts of the map which did not exist. Other environments, like gather, always had a fixed map size.

Obviously having the python process crash (not raise an exception, but just crash) is unacceptable so, I simply fixed the map size. 

So allowing different map sizes will require a careful design of the map creation method, and specific bounds where the map size works.

**Comment by jdpena** [comment]
@weepingwillowben understood, I'll go ahead and close the issue since it looks like it will be addressed in the forthcoming refactor.

**Comment by weepingwillowben** [comment]
@jdpena This has been implemented in full as a `map_size` argument and released.
