### ISSUE TITLE
PettingZoo Atari  ".spec" module

### ISSUE THREAD

**Issue by Ann-eat-apple** [PettingZoo-Team/PettingZoo#228]
Hello

I am a big fan of your repo. I am looking to see if there ".spec" for the Atari games. For instance, in the gym.make('Pong-v0'), its spec is:

```
gym.make('Pong-v0')
dir(env.spec)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_entry_point', '_env_name', '_kwargs', 'id', 'make', 'max_episode_steps', 'nondeterministic', 'reward_threshold', 'tags']

```

I am wondering if there anything equivalent for the MultiAgent Atari as well?

**Comment by weepingwillowben** [comment]
I'm glad you like our repo.

Currently there is no direct equivalent to this in PettingZoo. But what do you intend to use this feature for? We may be able to support your specific need.

**Comment by justinkterry** [comment]
Closed due to inactivity. Please let us know if you have any further issues!
