### ISSUE TITLE
Feature Request: Add render mode "ansi" for games which only render to console (use print function)

### ISSUE THREAD

**Issue by bkusenda** [PettingZoo-Team/PettingZoo#229]
Some of the environments only have the option to render in "human"  mode which uses print to output to stdout.  It would be really nice if these also included a render to string, "ansi", mode as well.  Though it is possible to redirect output to stdout using the contextlib.redirect_stdout, envs that print non-standard text characters, like backgammon, can have formatting issues.

**Comment by justinkterry** [comment]
You're right that that could be useful, but given other more pressing things we want to address with PettingZoo, I don't think we'll be able to do this in the near future. This is something we'd be open to a PR for, however.

**Comment by weepingwillowben** [comment]
PR #230 addresses this.

**Comment by justinkterry** [comment]
Right, so apparently we had already mostly done this internally. I merged the PR, sorry about the confusion.
