### ISSUE TITLE
HELP in converting MPE env to continuous.

### ISSUE THREAD

**Issue by Mithilesh8144** [PettingZoo-Team/PettingZoo#249]
How shall I convert the simple spread env from a discrete action space to a continuous action space?

**Comment by weepingwillowben** [comment]
1. Make sure you understand how to run the discrete MPE. I recommend taking a look at the [api](https://www.pettingzoo.ml/api) and [random demo](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/utils/random_demo.py). Write some code which uses the environment.
2. Make an argument `continuous_actions` to the MPE environment base class [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L24), and in all the subclasses for example [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/simple_adversary_v2.py#L7).
3. When the `continuous_actions` argument is true, change the action space [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L53), the wrappers [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L12) to [their continuous equivalents](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/waterworld/waterworld.py#L11), the way actions are interpreted [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L114) to the continuous version in [the original MPE ](https://github.com/openai/multiagent-particle-envs/blob/master/multiagent/environment.py#L144) (replacing the if statements there with `if self.continuous_actions`)
4. Test out these changes, make sure they make sense. Add to parameter unit tests [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/tests/all_parameter_combs.py#L83)
5. Add to documentation [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/docs/mpe/simple_reference.md#arguments)

**Comment by justinkterry** [comment]
If you get your changed into master and email me your address, I'll have a pizza of your choosing delivered to you

**Comment by Mithilesh8144** [comment]
> 1. Make sure you understand how to run the discrete MPE. I recommend taking a look at the [api](https://www.pettingzoo.ml/api) and [random demo](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/utils/random_demo.py). Write some code which uses the environment.
> 2. Make an argument `continuous_actions` to the MPE environment base class [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L24), and in all the subclasses for example [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/simple_adversary_v2.py#L7).
> 3. When the `continuous_actions` argument is true, change the action space [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L53), the wrappers [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L12) to [their continuous equivalents](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/sisl/waterworld/waterworld.py#L11), the way actions are interpreted [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L114) to the continuous version in [the original MPE ](https://github.com/openai/multiagent-particle-envs/blob/master/multiagent/environment.py#L144) (replacing the if statements there with `if self.continuous_actions`)
> 4. Test out these changes, make sure they make sense. Add to parameter unit tests [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/tests/all_parameter_combs.py#L83)
> 5. Add to documentation [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/docs/mpe/simple_reference.md#arguments)
> 
> Edit: steps 4 and 5 are only necessary if you wish to merge your code into the main project.

Apart from a few added changes, Works perfectly, Thank you!!

**Comment by Mithilesh8144** [comment]
Apart from a few extra changes to the code, the instructions worked perfectly, Thank you!!
