### ISSUE TITLE
Unable to load environments

### ISSUE THREAD

**Issue by Capitolhill** [PettingZoo-Team/PettingZoo#256]
I am unable to load almost all environments. Please see the image below.

![image](https://user-images.githubusercontent.com/24753433/100300365-d5b45380-2fd0-11eb-8ade-45cb6d1da09e.png)

I have tried for an hour now. Is it some issue at my end?

**Comment by weepingwillowben** [comment]
Sorry, the documentation is based off the master branch and is a little ahead of the release right now. 

The last attempt is the correct usage. Try:

```
from pettingzoo.butterfly import pistonball_v1
pistonball_v1.env()
```

**Comment by Capitolhill** [comment]
> 
> 
> Sorry, the documentation is based off the master branch and is a little ahead of the release right now.
> 
> The last attempt is the correct usage. Try:
> 
> ```
> from pettingzoo.butterfly import pistonball_v1
> pistonball_v1.env()
> ```

Thank you for the quick reply. I tried that as well. Environments either seem to not exist or have been deprecated.

![image](https://user-images.githubusercontent.com/24753433/100302674-c7b50180-2fd5-11eb-85d2-b6c3b0ee9192.png)

**Comment by justinkterry** [comment]
What version of PettingZoo are you using?

**Comment by Capitolhill** [comment]
> 
> 
> What version of PettingZoo are you using?

The (default) one that I got using **_pip install pettingzoo_**
![image](https://user-images.githubusercontent.com/24753433/100303949-ab669400-2fd8-11eb-87dc-51fa31ab5f84.png)

**Comment by weepingwillowben** [comment]
Looks like there was a screwup with the 1.4.1 release. I yanked the release, so 1.4.0 should be the default install from now on.

To fix this, you can manually downgrade to 1.4.0 with

```
pip install pettingzoo==1.4.0
```

And import the old environment versions as suggested above.

```
from pettingzoo.butterfly import pistonball_v1
pistonball_v1.env()
```

**Comment by weepingwillowben** [comment]
We will get out a new release with all the fixes soon.

**Comment by Capitolhill** [comment]
Thanks. That was a version problem, indeed. Pistonball_v1.env() does seem to work now.
However, other envs. like _knights_archers_zombies_v0.env()_ are still not working. 

![image](https://user-images.githubusercontent.com/24753433/100306011-524d2f00-2fdd-11eb-9f89-44825acdc267.png)

You might want to look into this.

**Comment by weepingwillowben** [comment]
In that case the documentation is just wrong. Thanks for bringing up these issues.

**Comment by weepingwillowben** [comment]
The example on the pettingzoo homepage should be fixed now
