### ISSUE TITLE
Custom environments 

### ISSUE THREAD

**Issue by Capitolhill** [PettingZoo-Team/PettingZoo#261]
Hi,

Is it possible to use a custom environment (with init, reset and step functions clearly defined) and train multiple agents to cooperatively maximize a global reward with PettingZoo? I am specifically seeking multi agent algorithmic implementations (like PPO, SAC etc.)- similar to what Stable-Baselines offer for a single agent in a custom environment. 

Following up this discussion (https://github.com/DLR-RM/stable-baselines3/issues/69#issuecomment-648079308),  I realized that this might be feasible, but I just can't see how to feed in the observation and action (which are, infact, dictionaries indexed by agent Ids) to the policies being trained.

Any suggestion or direction might help.

**Comment by justinkterry** [comment]
Perhaps I'm understanding the question, but this is all very simple. A global reward would just be handled by giving a reward to each agent per a global scheme in the environment. Many environments we have do this.

As for the second, I dont think I understand what you're asking. Our default observation and action spaces aren't dictionaries like that, they're stand alone (though the alternate parallel API behaves the same way). In the parallel API case though, you just assign policies an agent name and retrieve elements from dictionaries?

You might bennifit from reading this if you haven't: https://www.pettingzoo.ml/api

**Comment by weepingwillowben** [comment]
If you are looking for a plug and play implementation for baseline algorithms, we have integration with RLlib [documented here](https://docs.ray.io/en/master/rllib-env.html#pettingzoo-multi-agent-environments). Unfortunately the latest release hasn't been updated with critical fixes, so you will have to use the nightly build of ray.

**Comment by santiagoparaella** [comment]
Hi,
taking inspiration from the first question

In general I need to create a new environment (different from those in your project - a custom one?) in which I want to have many agents. 
There is some approaches in order to do this?

thank you in advance

**Comment by teo-tsou** [comment]
Hello,
I have the same question as @santiagoparaella . Is there any documented way or example to create a Custom Environment?

Thank you.

**Comment by WillDudley** [comment]
@teo-tsou There's documentation for this that is work in progress. In fact, I'll add it to the docs tomorrow with a disclaimer, as it's 80% complete

**Comment by teo-tsou** [comment]
@WillDudley Thank you very much for your quick response.

**Comment by WillDudley** [comment]
> @WillDudley Thank you very much for your quick response.

@teo-tsou No problem. The tutorials are now live on the PettingZoo website. Apologies that they're incomplete, I hope that together with the source code and asking questions in the discord server environment creation should be fairly straightforward.
