### ISSUE TITLE
[rllib] AttributeError: agents cannot be accessed before reset

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#266]
I'm updating some of my code to capture updates in PettingZoo and I'm running into the above error whenever I try to use `ray.rllib.env.PettingZooEnv`.

I thought it might be something from my custom code, but I get the same error when trying to run the pettingzoo-rllib example here: https://github.com/ray-project/ray/blob/master/rllib/examples/pettingzoo_env.py

__Note:__ the above example actually has another error that pops up first (`pettingzoo.utils.error.DeprecatedEnv: pistonball_v0 is now depreciated, use pistonball_v2 instead`), but this can be fixed easily by changing the import line to `from pettingzoo.butterfly import pistonball_v2`. Thought I would just flag it here while I was at it

**Comment by rallen10** [comment]
Not sure if there are adverse side effects, but a quick workaround seems to be a simple addition of `env.reset()` in [`env_creator`](https://github.com/ray-project/ray/blob/master/rllib/examples/pettingzoo_env.py), such as

```
def env_creator(config):
        env = pistonball_v2.env(local_ratio=config.get("local_ratio", 0.2))
        env = dtype_v0(env, dtype=float32)
        env = color_reduction_v0(env, mode="R")
        env = normalize_obs_v0(env)
        env.reset()
        return env
```

**Comment by justinkterry** [comment]
Are you using the nightly version of RLlib?

**Comment by weepingwillowben** [comment]
Yes, ray 1.0.1 is old and does not include needed fixes to the rllib pettingzoo wrapper. You can also just include the [code for that wrapper](https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py) into your own codebase as a workaround.

**Comment by rallen10** [comment]
Thanks for the feedback. I'm not using the nightly build of ray, so I can update that. However, even with the nightly build, I think the examples/pettingzoo_env.py needs updating (e.g. pistonball_v2)

**Comment by rallen10** [comment]
Hmmm. So I'm on ray version `'1.0.1.post1'` which was released on Nov 19th. The latest update to [the pettingzoo wrapper](https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py) was on Nov 9th. This makes me think that I already have the most up-to-date version of the wrapper and it's still causing the error

**Comment by weepingwillowben** [comment]
1.0.1.post1 was a patch release that only included a single commit over 1.0.1. So odd as it seems, it does not include the new wrapper. 

As you can see here: https://github.com/ray-project/ray/blob/ray-1.0.1.post1/rllib/env/pettingzoo_env.py

**Comment by rallen10** [comment]
Great! thank you for the heads-up! I'll try the nightly ray

**Comment by rallen10** [comment]
Installing [ray nightly build](https://docs.ray.io/en/master/installation.html#daily-releases-nightlies) seemed to do the trick with the caveat that I still had to change from `pistonball_v1` to `pistoball_v2
