### ISSUE TITLE
Adding the classic simultaneous move game called "Tron":

### ISSUE THREAD

**Issue by xkianteb** [PettingZoo-Team/PettingZoo#311]
Gitlab openai gym implementation: [https://gitlab.hs-ruhrwest.de/nico.zengeler/gym-tron]

Slides about the game: [https://www.researchgate.net/publication/341113059_The_Game_of_Tron_as_A_Reinforcement_Learning_Environment]

**Comment by justinkterry** [comment]
I don't think I understand your issue?

**Comment by xkianteb** [comment]
What is the process of getting a new environment added to the codebase? Should I submit a pull request or should I request that the environment be added?

**Comment by justinkterry** [comment]
Hey, similar to Gym we don't want to add new environments to PettingZoo proper. This would be better suited to a third party environment, like there are many of for Gym. If create it and it passes tests and so on we'd be happy to link to it, like Gym does for third party environments.
