### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by SachinKonan** [PettingZoo-Team/PettingZoo#314]
Traceback (most recent call last):
  File "test_piston_ball.py", line 64, in <module>
    observations, rewards, dones, infos = parallel_env.step(actions)
  File "/opt/conda/envs/marl/lib/python3.6/site-packages/pettingzoo/utils/to_parallel.py", line 36, in step
    self.aec_env.step(actions[agent])
  File "/opt/conda/envs/marl/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/opt/conda/envs/marl/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/opt/conda/envs/marl/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 156, in step
    super().step(action)
  File "/opt/conda/envs/marl/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/opt/conda/envs/marl/lib/python3.6/site-packages/pettingzoo/butterfly/pistonball/pistonball.py", line 388, in step
    global_reward = (100 / self.distance) * (self.lastX - ball_min_x)
ZeroDivisionError: division by zero

When the distance is zero, or self.lastX - self.wall_width = 0, then this error pops up.

**Comment by RyanNavillus** [comment]
Could you share the code you used to produce this error? `self.distance` is a very large number by default and does not change while acting in the environment. We haven't run into this issue in practice, but I'll look into it.

**Comment by SachinKonan** [comment]
Here is the code: `from pettingzoo.butterfly import pistonball_v3
from alex_net import Encoder
from policy import Policy, Experience
from torch.distributions import Categorical
import torch
import torch.optim as optim
from torch.autograd import Variable

#torch.autograd.set_detect_anomaly(True)

encoding_size = 100
action_space = 3
eps = 1e-3
lr = 0.0001
epochs = 100
n_agents = 5
max_cycles = 200

parallel_env = pistonball_v3.parallel_env(n_pistons=n_agents, local_ratio=0.9, time_penalty=-0.1, continuous=False,
                                          random_drop=True, random_rotate=True, ball_mass=0.75, ball_friction=0.3,
                                          ball_elasticity=1.5, max_cycles=max_cycles)


alex_encoder = Encoder()
policies = {agent: Policy(encoding_size, action_space) for agent in parallel_env.possible_agents}
optimizers = {agent: optim.Adam(policies[agent].parameters(), lr) for agent in parallel_env.possible_agents}

for epoch in range(0, epochs):
    print('Epoch: %s' % (epoch))
    observations = parallel_env.reset()
    for step in range(max_cycles):
        memory = {agent: Experience() for agent in policies.keys()}
        for agent, obs in observations.items():
            observations[agent] = alex_encoder(obs)

        policy_initial = {}
        for agent in policies.keys():
            initial_policy_distribution, state_val = policies[agent](observations[agent], None)
            memory[agent].state_val = state_val
            policy_initial[agent] = initial_policy_distribution

        actions = {}
        for agent in policies.keys():
            agent_num = int(agent.split('_')[1])
            neighbors = []
            for i in [-1,1]:
                if 0 <= agent_num + i < n_agents:
                    neighbors.append(policy_initial['piston_%d'%(agent_num+i)])
                    #neighbors.append(Variable(torch.zeros(policy_initial['piston_%d'%(agent_num+i)].shape)))
            output_states = policies[agent](policy_initial[agent], neighbors)
            final_policy_distribution = output_states[-1]
            if torch.equal(final_policy_distribution, torch.zeros(size=final_policy_distribution.shape)):
                final_policy_distribution = torch.ones(size=final_policy_distribution.shape)*eps
            distribution = Categorical(logits=final_policy_distribution)
            action = distribution.sample()
            log_prob = distribution.log_prob(action)
            action = action.item()

            memory[agent].action = action
            memory[agent].log_prob = log_prob
            memory[agent].policy_distribution = final_policy_distribution
            actions[agent] = action

        observations, rewards, dones, infos = parallel_env.step(actions)
        for agent in policies.keys():
            memory[agent].rewards = rewards[agent]
            if memory[agent].check():
                policies[agent].add_to_memory(memory[agent])
            else:
                print('\tOn Iteration: %d, agent: %d, failed its memory test' % (step, agent))

        if all([v is True for v in dones.values()]):
            break

    for agent in policies.keys():
        optimizers[agent].zero_grad(set_to_none=False)

    for agent in policies.keys():
        loss, avg_reward = policies[agent].compute_loss()
        print('\t Avg Reward for %s: %f' % (agent, avg_reward))
        loss.backward(retain_graph=True)

    print('\t *Overall Number of Iterations: %s' % (step))
    for agent in policies.keys():
        optimizers[agent].step()

    for agent in policies.keys():
        policies[agent].clear_memory()`

The encoder and policies aren't too important. The policies just return a distribution, where an action is sampled from each agent. Maybe it is because I am using the 5 piston example?

**Comment by justinkterry** [comment]
Hey this isn't related to the original issue (I'll look into that more and reply in a bit), but why did you set local_ratio=.9?

**Comment by SachinKonan** [comment]
I am trying to do decentralized multi-agent learning, so I wanted the local rewards to have a larger effect than the overall global reward.

**Comment by RyanNavillus** [comment]
Thanks for pointing this issue out. Occasionally when the number of pistons is very low, the ball will spawn at position 40, resulting in `self.distance` equaling 0 (In fact, it could spawn inside the left wall). I added a check to prevent this in #315

**Comment by SachinKonan** [comment]
Thanks!
