### ISSUE TITLE
random_demo rendering problem

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/PettingZoo#325]
One problem that I didn't fix in PR #324 is that random demo depends on env.display_wait, which is documented nowhere and isn't part of the API, and without it sets display_wait to 0, which will likely result in undesirable behavior. This even happens without warning. Someone should probably do something about this.

**Comment by justinkterry** [comment]
Wait, this is only even used in multiwalker and waterworld should be handled by render anyways. @weepingwillowben should I just remove all of that?

**Comment by weepingwillowben** [comment]
Yeah, display_wait being part of the environment is probably not a feature we should support. I am a believer that the user should decide how much delay to put between frames.

**Comment by justinkterry** [comment]
Removed in #324
