### ISSUE TITLE
Issue when trying to render

### ISSUE THREAD

**Issue by NawelAr** [PettingZoo-Team/PettingZoo#338]
Hello, 

I am trying to run the 15 lines tutorial,  I get this error with this line 

`   env.step(act)
`
AttributeError: 'tuple' object has no attribute 'shape'

How can it be fixed ?

PS: I am working on colabs

**Comment by justinkterry** [comment]
Please include your:

-The full code/traceback
-Your pip freeze
-What the act tuple looks like

**Comment by justinkterry** [comment]
Wait you can't render in google collab. Render draws a window on your screen, it requires being run on a system with a GUI. This is some inelegant code I have for using render to generate a gif (with a different learning library) that you can adapt to the tutorial.


```
from array2gif import write_gif

reward_sum = 0
obs_list = []
i = 0
env.reset()

while True:
    for agent in env.agent_iter():
        observation, reward, done, info = env.last()
        reward_sum += reward
        if done:
            action = None
        else:
            action, _, _ = PPOagent.get_policy("policy_0").compute_single_action(observation)

        env.step(action)
        i += 1
        if i % (len(env.possible_agents)+1) == 0:
            obs_list.append(np.transpose(env.render(mode='rgb_array'), axes=(1, 0, 2)))
    env.close()
    break


print(reward)
write_gif(obs_list, 'pistonball_160.gif', fps=15)
```

**Comment by pamikem** [comment]
> Please include your:
> 
> -The full code/traceback
> -Pip freeze output
> -What the act tuple looks like

Hi @justinkterry ! Please find attached some screenshots showing the traceback of the error.
 

![Capture d’écran (41)](https://user-images.githubusercontent.com/51324356/109426096-f931d480-79eb-11eb-9150-b167ca8de385.png)
![Capture d’écran (42)](https://user-images.githubusercontent.com/51324356/109426097-f9ca6b00-79eb-11eb-9465-c0cf208bf0e1.png)
![Capture d’écran (43)](https://user-images.githubusercontent.com/51324356/109426098-f9ca6b00-79eb-11eb-9128-7f14f7412f1f.png)
![Capture d’écran (44)](https://user-images.githubusercontent.com/51324356/109426101-fa630180-79eb-11eb-8095-f0ee3c49e5a9.png)

**Comment by weepingwillowben** [comment]
So I'm not sure if it is an old version of stable baselines that is causing it or what. however, you should be able to fix this issue with 

```
act = model.predict(obs)[0]
```

**Comment by weepingwillowben** [comment]
Here is a complete working example of training leduc holdem with ray 1.2.0 and latest version of pettingzoo: https://gist.github.com/weepingwillowben/7ea33e31d31a819d25bf64fb2bf1d430

It ensures that illegal actions are not taken, except when doing epison greedy. If you convert this to an algorithm with a different exploration method, then you should be able to get it to not take illegal actions at all.
