### ISSUE TITLE
Warnings raised on close() in normal situations

### ISSUE THREAD

**Issue by weepingwillowben** [PettingZoo-Team/PettingZoo#341]
In gym environments, `.close()` is not just for rendering, but potentially for releasing any environment resources, such as subprocesses, network connections, etc. It is good practice to close any environment. So these warnings should not be there: https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/utils/wrappers/order_enforcing.py#L47

**Comment by justinkterry** [comment]
So close doing this is news to me, and Im certainly one who would know these things. 

-Why should this be handled by close?
-This is not a documented or widely used feature in Gym or PettingZoo to my knowledge

**Comment by justinkterry** [comment]
"To be sure I'm not completely sure this is a good use of the close() method, as you might want to close the rendering window without destroying the whole environment object."

If memory serves, that was my exact line of reasoning when I wrote that test. The fact that close is used in commonplace for that honestly kinda concerns me.

Perhaps the solution is to remove the warning but let it remain a terrible idea to do?

**Comment by weepingwillowben** [comment]
Sounds good to me.
