### ISSUE TITLE
13_lines.py doesn't work with stable_baselines3

### ISSUE THREAD

**Issue by APN-Pucky** [PettingZoo-Team/PettingZoo#350]
however reverting to cfff5c883c2084d8388ecf5d6b333dba33f8eb71 works for me.

**Comment by justinkterry** [comment]
What error message are you getting, and are you sure you're using the newest version of supersuit?

**Comment by APN-Pucky** [comment]
from stable_baselines3.common.policies import CnnPolicy
ImportError: cannot import name 'CnnPolicy' from 'stable_baselines3.common.policies'

same for PPO2.
```python
>>> import supersuit
>>> supersuit.__version__
'2.6.1'
>>> import stable_baselines3
>>> stable_baselines3.__version__
'0.11.1'
```

**Comment by APN-Pucky** [comment]
Maybe this is due to the fact that stable_baselines3 finished their beta ~2 weeks ago: https://github.com/DLR-RM/stable-baselines3/releases

**Comment by justinkterry** [comment]
Sorry for the delayed reply.

Yes this was caused by that. I updated the file and medium article, but apparently SB3 has another feature breaking the supersuit wrapper that we need to fix.

**Comment by justinkterry** [comment]
a fix to supersuit was released this morning so everything should be good now, sorry for the delayed reply
