### ISSUE TITLE
API Test Not working 

### ISSUE THREAD

**Issue by juansebastianl** [PettingZoo-Team/PettingZoo#354]
I was running the API test on a custom game I created and I got the following error: 

```TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''```

Which I think is coming from the fact that my observation space is a dictionary instead of a Box, and so numpy can't asses if it's infinite.

**Comment by weepingwillowben** [comment]
Hi Juan, I'm glad you are interested in creating a custom pettingzoo environment. 

Right now, we have classic environments which output a dictionary observation, and in these environments, the api_test prints

```
api_test.py:37: UserWarning: Observation is not NumPy array
  warnings.warn("Observation is not NumPy array")
```

And it skips the isinf check for the observation. 

Can you give some more information about what line your error is on and what your observations look like and observation space is?

**Comment by juansebastianl** [comment]
It's a bit complicated, but I have two different agent types, so I set up their observation spaces individually: 

      p0_observations = {agent: spaces.Dict({'o1': Box(low=-np.Inf, 
                                                            high=np.Inf,
                                                            shape=(1,), dtype=np.float32),
                                           'o2': Box(low=-np.Inf, 
                                                            high=np.Inf,
                                                            shape=(1,), dtype=np.float32),
                                            'o3': Box(low=-np.Inf, 
                                                            high=np.Inf,
                                                            shape=(1,), dtype=np.float32)})
                                           for agent in p0_agents}

        p1_observations = {agent: spaces.Dict({'o4': Box(low=-2.0, 
                                                                    high=2.0,
                                                                    shape=(1,), dtype=np.float32),
                                                   'o5': spaces.Box(low= -2.0, 
                                                                        high= 2.0, 
                                                                        shape=(n_politicians,), dtype=np.float32), 
                                                    'o6': Box(low=-np.Inf, 
                                                            high=np.Inf,
                                                            shape=(1,), dtype=np.float32), 
                                                    'o7': Box(low=-np.Inf, 
                                                            high=np.Inf,
                                                            shape=(1,), dtype=np.float32)) 
                                           for agent in p2_agents}

And then I setup the total thing by saying `self.observations = {**p0_observations, **p1_observations}`

I get the error with the following output: 

     Starting API test
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
       File "/home/usr/.local/lib/python3.8/site-packages/pettingzoo/test/api_test.py", line 232, in api_test
         test_observation(observation_0, observation_0)
       File "/home/usr/.local/lib/python3.8/site-packages/pettingzoo/test/api_test.py", line 14, in test_observation
         if np.isinf(observation).any():
     TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by weepingwillowben** [comment]
Thanks for the additional information. 

The reason I am a little confused about your error is that right above line 14 which is giving the error there is an if statement 

```
    if isinstance(observation, np.ndarray):
        if np.isinf(observation).any():
```
here: https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/test/api_test.py#L13

So if it was really a dictionary, it would not be running that line. 

Given that, I would guess that the observation is being coerced into an numpy object array. For example:

````
>>> import numpy as np
>>> np.array({"hi":"there"})
array({'hi': 'there'}, dtype=object)
````

Maybe you can print out a result of your observe function and see if it is one of these weird coerced numpy object arrays

**Comment by juansebastianl** [comment]
Interesting, here is what the observe produces: 

      env.observe(env.agents[0])
      >>> array({'o1': 1.8876158408505201, 'o2': array([-1.72791348, -1.86190396])},
      dtype=object)

**Comment by weepingwillowben** [comment]
Yes, that is your problem. Try to track down where the dictionary gets converted to a numpy array and make sure it doesn't happpen.

**Comment by justinkterry** [comment]
Just out of curiosity could you link me to the repo of your environment?

**Comment by justinkterry** [comment]
Hey I'm going to close this, let us know if you have anymore problems
