### ISSUE TITLE
render_test does not support custom render modes

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [PettingZoo-Team/PettingZoo#368]
`render_test` only supports the render modes `'human'`, `'ansi'` and `'rgb_array'`. A custom environment I am developing supports rendering the environment as `'svg'`. Extending `render_test` to support custom render modes would be useful, since the render mode names are not standardized across various environments. Here's a partial list of `render.modes` from popular repositories not covered in the supported list -

* OpenAI Gym Environments
  * [`'depth_array'`](https://github.com/openai/gym/blob/38a1f630dc9815a567aaf299ae5844c8f8b9a6fa/gym/envs/mujoco/mujoco_env.py#L54) in `mujoco/mujoco_env`
  * [`'state_pixels'`](https://github.com/openai/gym/blob/c8a659369d98706b3c98b84b80a34a832bbdc6c0/gym/envs/box2d/car_racing.py#L118) in `box2d/car_racing`
* Kaggle Environments
  * `'webm'`, `'json'`, `'html'` in [kaggle-environments](https://github.com/Kaggle/kaggle-environments/blob/24a2cea763fe5d68a9f0f4c90b66d13801650316/kaggle_environments/main.py)

**Comment by justinkterry** [comment]
I'll let Ben respond to this in technical detail, but is your environment public? I would really like to see an environment that the sensible way to render is with svg

**Comment by weepingwillowben** [comment]
I'm glad you are interested in making a custom environment.

I agree, the current render_test is overspecialized to the current set of pettingzoo environments. I would be happy to update it to be more accommodating of custom environments and render modes. 

I think the appropriate test of a render mode is to:

1. Try rendering the environment for a few steps. If it crashes, then the test obviously fails.
2. If the mode is an official mode i.e. `ansi`, `rgb_array`, `human`, then it checks the output type (str, ndarray, None). Otherwise, it assumes the return value is correct.

Do you agree that this level of testing is appropriate or do you think we really need explicit support of all these different render modes? I guess I want to avoid having to continually add support for new render modes as they come along.

**Comment by AbhijeetKrishnan** [comment]
It is perfectly fine to support just `ansi`, `rgb_array` and `human`. I think your two steps are reasonable. Optionally, if the checks for the official modes just involve checking the return value type, perhaps an optional arg allowing a dictionary of `render_modes` to expected return types could be passed. I've written a rough version of what I envision below. 

There could be args to handle additional checks like how the size of the `rgb_array` is checked (perhaps a custom function which returns `bool` that gets asserted)

```python
def render_test(env, render_mode_types_dict):
    render_modes = env.metadata.get('render.modes')
    ...
    for mode in render_modes:
        # assert (mode in {"human", "ansi", "rgb_array"})
        env.reset()
        ...
            if mode == "human":
                assert res is None
           if mode in render_mode_types_dict.keys():
               assert isinstance(res, render_mode_types_dict[mode]) # or assert render_mode_checking_function[mode]
        env.reset()
    env.close()
```

**Comment by AbhijeetKrishnan** [comment]
> I'll let Ben respond to this in technical detail, but is your environment public? I would really like to see an environment that the sensible way to render is with svg

The repo is [here](https://github.com/AbhijeetKrishnan/fanorona-aec). It is an implementation of a board game called Fanorona, and is right in line with the other classic envs. I was unable to design a suitable text-based representation of the board like in chess, and so decided to go with an svg-based representation. Representing the board as an RGB-image is perfectly feasible, but I am not going to use it for training and it is purely to help a human visualize the board.

**Comment by weepingwillowben** [comment]
I made a PR for this #369 . Let me know what you think.

**Comment by AbhijeetKrishnan** [comment]
`collect_render_results` would definitely help me write tests for checking that my custom `svg` rendering mode works. I'm happy if #371 gets merged. 

As a closing thought, I feel that as a matter of API design, `render_test` is not doing what it says on the box. The dev of a future custom environment with a non-standard render mode would have to use `collect_render_results` to test that their render mode is working (along with some external checker function). I feel it would be more intuitive to have `render_test` itself support this functionality. I've created a draft PR ([#372](https://github.com/PettingZoo-Team/PettingZoo/pull/372)) which implements this here.
