### ISSUE TITLE
Multiwalker environment crash

### ISSUE THREAD

**Issue by DriesSmit** [PettingZoo-Team/PettingZoo#376]
Good day,

I am currently having an issue with the multiwalker environment inside PettingZoo. When my agents solve the environment (reaches the final timestep) the code seems to crash inside PettingZoo. I think I may know what is causing it to crash. 

Inside the file
[https://github.com/PettingZoo-Team/PettingZoo/blob/b6a386eac26ff10b499e75b0f5eee7c57bd56f07/pettingzoo/sisl/multiwalker/multiwalker_base.py#L470](url)
on line 477 last_dones is set to a boolean value. Should this line not read 
`self.last_dones = [True for _ in range(self.n_walkers)]` ?

Thanks you for your time,
Dries

**Comment by weepingwillowben** [comment]
Hi, I'm glad you have found the multiwalker environment. 

I tracked down the error from the line you pointed out and fixed it in #377.

Can you confirm that this solves the issue? We have not been able to solve multiwalker yet, so it is hard to test it.

If this fixes the issue, then expect a release with this fix immediately.

**Comment by DriesSmit** [comment]
The fix looks good, thanks!

**Comment by DriesSmit** [comment]
Hello. Thanks for the quick response :)
Yes that should fix the problem.

**Comment by justinkterry** [comment]
How were you able to solve the environment?

**Comment by weepingwillowben** [comment]
This issue has been fixed and released in pettingzoo 1.8.2.

Note that this change bumped the environment version, so now you will need to use multiwalker_v7.

**Comment by DriesSmit** [comment]
Thanks @benblack769! @justinkterry we used MA-D4PG to solve the environment. It seems to work well :)

**Comment by justinkterry** [comment]
If you have the code public could you link me to it?

**Comment by DriesSmit** [comment]
@justinkterry I can give you the code in a few weeks if you still want it by then :)

**Comment by justinkterry** [comment]
That'd be great, thank you

**Comment by DriesSmit** [comment]
@jkterry1 Apologies for the wait. We just released our Mava framework to the public ([Mava](https://github.com/instadeepai/Mava)). In the repo you will find the multiwalker example we used ([example](https://github.com/instadeepai/Mava/blob/develop/examples/petting_zoo/sisl/multiwalker/feedforward/decentralised/run_mad4pg.py)). Any feedback is welcome :)
