### ISSUE TITLE
Parallel classic games

### ISSUE THREAD

**Issue by TylerJamesMalloy** [PettingZoo-Team/PettingZoo#378]
I tried to edit one of the classic games, mahjong, to allow for a parallel environment run as follows:

`parallel_env = parallel_wrapper_fn(env)`

into the mahjong.py file. 
I also added some required parameters but it still doesn't work

> AttributeError: Can't pickle local object 'vec_env_args.<locals>.env_fn'
Exception ignored in: <bound method ProcConcatVec.__del__ of ProcConcatVec(32)>
Traceback (most recent call last):
  File "C:\Users\Tyler\.conda\envs\py361\lib\site-packages\supersuit\vector\multiproc_vec.py", line 153, in __del__
    for pipe in self.pipes:
AttributeError: 'ProcConcatVec' object has no attribute 'pipes'
(py361) PS C:\Users\Tyler\Desktop\Projects\NeurIPS\macc> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Tyler\.conda\envs\py361\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Tyler\.conda\envs\py361\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by TylerJamesMalloy** [comment]
This appears to be related to the following: 

https://github.com/PettingZoo-Team/SuperSuit/issues/75

I believe the issues is due to using Windows.

**Comment by benblack769** [comment]
@TylerJamesMalloy 

Some relevant advice:

1. Do not use multiprocessing unless you have good reason to belive it will improve performance. Which it will probably not on Mahjong. This will solve this crashing error.
2. Mahjong makes no sense as a parallel environment. It definitely does not make sense as a vector environment. Do not try to learn it with stable baselines.
3. For RL beginners, we recommend using rllib on classic environments. For example, this code snippet trains a ludic holdem environment. You should be able to port it to mahjong easily: https://gist.github.com/benblack769/6136ff1c941ddb81b82030621d83ed92

**Comment by justinkterry** [comment]
A side note comment is that PettingZoo, and most ML libraries, don't fully support Windows. E.g. this is PettingZoo's policy:

"We support Python 3.6, 3.7, 3.8 and 3.9 on Linux and macOS. We will accept PRs related to Windows, but do not officially support it."
