### ISSUE TITLE
rps_v1.parallel_env() not work for classis games

### ISSUE THREAD

**Issue by quantumiracle** [PettingZoo-Team/PettingZoo#379]
Hi,
In the documentation (https://www.pettingzoo.ml/classic/rps) it writes "Parallel API Yes", while in practice when I used `env = rps_v1.parallel_env()` it reports an error:
```
AttributeError: module 'pettingzoo.classic.rps_v1' has no attribute 'parallel_env'
```

**Comment by justinkterry** [comment]
Hey, RPS and rpsls actually should support that. We have a planned overhaul of those environments this month and will address that then.

**Comment by justinkterry** [comment]
Does this work for you?

https://github.com/PettingZoo-Team/PettingZoo/pull/380

**Comment by quantumiracle** [comment]
Yes, it works now. Thanks!
