### ISSUE TITLE
How can we make sure all agents choose actions in one step ?

### ISSUE THREAD

**Issue by caozixuan** [PettingZoo-Team/PettingZoo#381]
I want to let agents choose actions step by step in the environment.

for agent in env.agent_iter():
    observation, reward, done, info = env.last()
    action = policy(observation, agent)
    env.step(action)

if I use the code above, can I know that one step is over and jump out of the loop?

**Comment by benblack769** [comment]
Can you clarify this question a bit more?

What d you mean by a step? Why do you want to jump out of the loop once a step is over? Can't you just stay in the loop until it ends (when the environment is done?)

**Comment by justinkterry** [comment]
Hey, I'm going to close this due to inactivity. If you need anything else let us know.
