### ISSUE TITLE
How to choose convolution filters for Battlefield env (Magent)

### ISSUE THREAD

**Issue by george-skal** [PettingZoo-Team/PettingZoo#382]
Hi!,
I am trying to use the battlefield environment with Rllib (maybe this is also an RLlib question but I post here because it is environment speciifc). I want to ask what values should I put to the "conv_filters" parameter needed for the environment to work.
From what I have found the "conv_filters" is a list of [out_channels, kernel, stride], but I am not sure about the specific values and the number of filters I should use. I tried a convolution filter but I get the error: TypeError: 'int' object is not subscriptable
The observation shape is (13,13,5).
I am not very familiar with CNNs, so I appreciate any help.
Thanks in advance,
George

Please find attached the code I am working on:

```
from ray import tune
from ray.rllib.agents.callbacks import DefaultCallbacks
import argparse
import gym
import os
import random
import ray
from ray.tune.registry import register_env
from ray.rllib.env.wrappers.pettingzoo_env import PettingZooEnv
from pettingzoo.magent import battlefield_v3
from supersuit import pad_observations_v0

if __name__ == "__main__":

    ray.init()

    def env_creator(args):
        env = battlefield_v3.env(map_size=80, minimap_mode=False, step_reward=-0.005, dead_penalty=-0.1,
                                 attack_penalty=-0.1, attack_opponent_reward=0.2, max_cycles=1000, extra_features=False)
        env = pad_observations_v0(env)
        return env

    register_env("battlefield", lambda args: PettingZooEnv(env_creator(args)))

    test_env = PettingZooEnv(env_creator({}))
    obs_space = test_env.observation_space
    act_spc = test_env.action_space

    policies = {"shared_1": (None, obs_space, act_spc, {}),
                "shared_2": (None, obs_space, act_spc, {})
                }

    def policy_mapping_fn(agent_id):
        if agent_id.startswith("red") == True:
            return "shared_1"
        else:
            return "shared_2"

    tune.run(
        "PPO",
        stop={"episodes_total": 50000},
        checkpoint_freq=10,
        config={
            "model": {
                "dim": 13,
                "conv_filters": [
                    [5, 13, 1]
                ]
            },
            # Enviroment specific
            "env": "battlefield",
            # General
            "framework": "torch",
            "num_gpus": 0,
            "num_workers": 0,
            # Method specific
            "multiagent": {
                "policies": policies,
                "policy_mapping_fn": policy_mapping_fn,
            },
        },
    ) 
```

**Comment by benblack769** [comment]
For the syntax, refer to the example here: https://docs.ray.io/en/master/rllib-models.html?highlight=conv_filters#built-in-models

For what values to use, you can refer to the original magent implmentations for the workshop demo in their repo, for example here: https://github.com/geek-ai/MAgent/blob/b1fce2799bacd1d29f4a14b3196abc56425a6e6b/python/magent/builtin/mx_model/dqn.py#L136

Note that there are differences between the original environment and our environment. See the documentation https://www.pettingzoo.ml/magent/battle. In particular, to get as close to the original implementation as possible set minimap_mode and extra_features arguments to true.

**Comment by george-skal** [comment]
Dear @benblack769 ,
Thanks for the links.
If I understand correctly the intial convolution scheme was 2 conv layers with 32 filters (kernels), kernel size: (3,3) and stride = 1 (default) and also 256 fc layers after that.
I tried this scheme but RLlib thows the error (without the 256 fc layers in the end):

> (pid=16084) ValueError: Given `conv_filters` ([[32, [3, 3], 1], [32, [3, 3], 1]]) do not result in a [B, 21 (`num_outputs`), 1, 1] shape (but in [32, 21, 11, 11])! Please adjust your Conv2D stack such that the last 2 dims are both 1.

After some trial and error I found that the code runs with 3 conv layers with 32 filters and stride = 2. (see code below)
But I am not sure if this works correctly or the 32 filters find the correct attributes. Can you tell me if this is fine or I should try another combination? 

Also, have you or others in Pettingzoo tested a convolution scheme for battlefiend for RLlib (since the environmnet is compattible with RLlib)?

Also. you told me to enable extra_features etc if I want to be closer to the old environment, but I don't want to compare with something older, so how do I choose the convolution parameters if I want to work with the new version of Battlefield?
Thanks in advance!

Here is the code that runs without error:

```
from ray import tune
import ray
from ray.tune.registry import register_env
from ray.rllib.env.wrappers.pettingzoo_env import PettingZooEnv
from pettingzoo.magent import battlefield_v3
from supersuit import pad_observations_v0

if __name__ == "__main__":

    ray.init()

    def env_creator(args):
        env = battlefield_v3.env(map_size=80, minimap_mode=False, step_reward=-0.005, dead_penalty=-0.1,
                                 attack_penalty=-0.1, attack_opponent_reward=0.2, max_cycles=1000, extra_features=False)
        env = pad_observations_v0(env)
        return env

    register_env("battlefield", lambda args: PettingZooEnv(env_creator(args)))

    test_env = PettingZooEnv(env_creator({}))
    obs_space = test_env.observation_space
    act_spc = test_env.action_space

    policies = {"shared_1": (None, obs_space, act_spc, {}),
                "shared_2": (None, obs_space, act_spc, {})
                }

    def policy_mapping_fn(agent_id):
        if agent_id.startswith("red") == True:
            return "shared_1"
        else:
            return "shared_2"

    tune.run(
        "PPO",
        stop={"episodes_total": 50000},
        checkpoint_freq=10,
        config={
            "model": {
                "post_fcnet_hiddens": [256],
                "conv_filters": [
                    [32, [3, 3], 2],
                    [32, [3, 3], 2],
                    [32, [3, 3], 2]
                ],
            },
            # Enviroment specific
            "env": "battlefield",
            # General
            "framework": "torch",
            "num_gpus": 0,
            "num_workers": 0,
            # Method specific
            "multiagent": {
                "policies": policies,
                "policy_mapping_fn": policy_mapping_fn,
            },
        },
    )
```

**Comment by justinkterry** [comment]
Hey, I'm going to close this due to inactivity, let us know if you need any problems with the library.
