### ISSUE TITLE
What is the expected behaviour of agents in ParallelEnv

### ISSUE THREAD

**Issue by 51616** [PettingZoo-Team/PettingZoo#387]
I'm trying to use PettingZoo interface to create my own custom environment. I did look through the dev docs [here](https://www.pettingzoo.ml/dev_docs). While it is clear on how to implement a simple game like RPS where agents terminate at the same time, I am not sure about the intended behaviour of ParallelEnv. 

Particularly, when an agent is terminated (done flag is true), is that agent expected to be removed from the observation dict entirely? Is it ok to have some agents skip some timesteps (waiting but not terminated) and then come back and interact again? Or is it possible to resurrect terminated agents?
I try to see the [test code](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/test/parallel_test.py) but I guess it makes some assumptions about the termination/observation behavior which I'm not certain what they are. For example, it tests that `env.agents` has the same number of agents as the observation dict. What's the implication of that? Can `env.agents` add/remove agents during an episode? Can you please clarify the assumptions about ParallelEnv or, even better, compared it against the behavior of AECEnv?

Btw, thank you for such a cool lib for MARL :)

Edit: `env_done` is checked in the test but not mentioned in the doc as well. Also, isn't `live_agents` in the test supposed to be updated before checking `assert par_env.agents == live_agents`?

**Comment by benblack769** [comment]
The idea is that:

1. An agent is in the environment until after it has been done. So when step returns that an agent is done, it will still be in the observations dict, etc. However, after it steps again, it will be removed from the `env.agents` list, and the observations, dones, etc dictionaries. This is why the live_agents list is updated in a bit of a weird way. Agents which are done, but have not stepped again yet are still "live" in that they are still in the `.agents` list.
2. `env_done` is defined here: https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/utils/env.py#L256. It is also deprecated, I would not advise using it.  Just use `not env.agents`

If you want, you can look at the source code for the [MAgent environment](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/magent/magent_env.py#L130) or the [Atari environment](https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/atari/base_atari_env.py#L148) which implement the parallel environment API.
