### ISSUE TITLE
Receive more than 200 rewards in the MultiWalker environment 

### ISSUE THREAD

**Issue by wenwenla** [PettingZoo-Team/PettingZoo#392]
The reinforcement learning algorithm received more than 200 cumulative rewards in the MultiWalker environment with 2 agents.
It might be a bug in the environment (or just a feature? ).
It was caused by the agent at the back surpasses the agent at the front without collision.
A video can be viewed here.

![Video_2021-05-29_114057](https://user-images.githubusercontent.com/26131986/120057185-b5df1480-c073-11eb-91ba-ff2e2c911515.gif)

**Comment by benblack769** [comment]
I made a PR to fix the issue where robots can walk through each other #396
