### ISSUE TITLE
ANSI render failing for connect4

### ISSUE THREAD

**Issue by PWieck** [PettingZoo-Team/PettingZoo#414]
The following code snippet:
```
env = connect_four_v3.env()
env.reset()
env.render(mode='ansi')
```

Fails on the last line with error:

```
File "C:\Users\wieck\AppData\Local\Programs\Python\Python39\lib\site-packages\pettingzoo\utils\wrappers\order_enforcing.py", line 43, in render
    assert mode in self.metadata['render.modes']
AssertionError
```

**Comment by benblack769** [comment]
So we are changing the rendering for a lot of the classic environments from text based to graphical, and we are dropping support for the `ansi` render mode in the process. Please look at using the `rgb_array` render mode instead. Also make sure to use the latest version of the master branch, there have been some very recent fixes to `rgb_array` handling.

**Comment by justinkterry** [comment]
Let us know if you have any further issues
