### ISSUE TITLE
Frame stacking by default in chess and go

### ISSUE THREAD

**Issue by benblack769** [PettingZoo-Team/PettingZoo#425]
Chess and go currently only store the last game state. Like the aphazero paper, they should store the previous 8 game states. See table S1 in the alphazero paper: https://arxiv.org/pdf/1712.01815.pdf for more details.

This should not be very hard, we just need to track a 8 length list of the board state observations (the first row of the S1 table in the paper), and concatenate them with the game state observations (the second row of the S1 table).

**Comment by jkterry1** [comment]
Closed by PR#40
