### ISSUE TITLE
When is the agent done in the Pursuit Env?

### ISSUE THREAD

**Issue by LINGYUNFDU** [PettingZoo-Team/PettingZoo#427]
Hi, 
Thanks for your great contribution! However, I am still confused when I was trying to find the conditions for the agents to be done. 

First, I found all the agents will be done in the test even though only one agent caught the evader. It is not reasonable as the other pursuers should still move.

Second, if we need to reset the env manually after the agents are done? Or it can automatically perform a reset?

Thanks for your reply!

**Comment by benblack769** [comment]
As per [the documentation](https://www.pettingzoo.ml/sisl/pursuit), the environment terminates after the environment takes 500 cycles, or when there are no more evaders left, whichever comes first. You can set the `max_cycles` argument to be more than 500 if you wish the environment to run for longer. I updated the documentation in #428 to hopefully make this a bit more clear.

**Comment by benblack769** [comment]
And yes, like gym environments, you will need to manually reset the environment.

**Comment by jkterry1** [comment]
Let us know if you have anymore questions
