### ISSUE TITLE
Observation and action spaces defined by functions not dictionaries

### ISSUE THREAD

**Issue by benblack769** [PettingZoo-Team/PettingZoo#441]
In order to more easily support dynamically generated agents, we plan to replace observation spaces and action spaces dictionaries with observation_space and action_space function that take in agent ids.

* deprecation plan
  * observation_spaces and action_spaces raises deprecation warning when accessed by wrappers
  * default implemenetation of observation_space and action_space functions access the observation_spaces and action_spaces dictionaries. Can be overridden by base function.
* rllib plan
  * construct action_spaces and observation_spaces dictionaries to give to rllib's API by passing in each element of possible_agents to the observation_space function.
* Mava/ALL plan
  * investigate, come back with more details

**Comment by jkterry1** [comment]
Done in #489
