### ISSUE TITLE
There seems a mistake in pistonball.py leading to pygame display mode error

### ISSUE THREAD

**Issue by LzYzL** [PettingZoo-Team/PettingZoo#443]
def render(self, mode="human"):
        if mode == 'human' and not self.renderOn:
            # sets self.renderOn to true and initializes display
            self.enable_render

        self.draw_background()
        self.draw()

        observation = np.array(pygame.surfarray.pixels3d(self.screen))
        if mode == 'human':
            pygame.display.flip()
        return np.transpose(observation, axes=(1, 0, 2)) if mode == "rgb_array" else None_

There should be "( )" behind enable_render,otherwise it will lead to **pygame.error: Display mode not set** because the pygame display mode have not been initiallized.

_def render(self, mode="human"):
        if mode == 'human' and not self.renderOn:
            # sets self.renderOn to true and initializes display
            self.enable_render('human')

        self.draw_background()
        self.draw()

        observation = np.array(pygame.surfarray.pixels3d(self.screen))
        if mode == 'human':
            pygame.display.flip()
        return np.transpose(observation, axes=(1, 0, 2)) if mode == "rgb_array" else None_
I modified it in this way and it works normally now.

**Comment by jkterry1** [comment]
I've always just added a line to learning code to get rid of the error because I didn't know how to fix this. @benblack769 could you please look into this and do a PR for all the pygame environments?

**Comment by benblack769** [comment]
Thanks for identifying this mistake! I have a patch in #444
