### ISSUE TITLE
Rethinking done agents in parallel env

### ISSUE THREAD

**Issue by benblack769** [PettingZoo-Team/PettingZoo#464]
The way that the `agents` list is handled in parallel environments is a continual problem (see https://github.com/instadeepai/Mava/issues/297 for example).

Instead, the `agents` list should contain the set of agents that need to take actions in the next step, or perhaps should be removed entirely. @jkterry1  Thoughts?

**Comment by jkterry1** [comment]
I think having a list of active agents is meaningfully useful, but ascribing order in the parallel API is inherently meaningless. Maybe we should keep it and make it a tuple?

**Comment by KaleabTessera** [comment]
@benblack769 @benblack769 For our specific use case (the PZ Smac Wrapper), the issue was when the `agents` list gets updated. The list got updated before getting the latest dones, causing various issues.  I proposed a fix for this in the Mava thread (https://github.com/instadeepai/Mava/issues/297).

**Comment by jkterry1** [comment]
Done in #489
