### ISSUE TITLE
Incorrect game description on webpage

### ISSUE THREAD

**Issue by TylerJamesMalloy** [PettingZoo-Team/PettingZoo#479]
The classic game no limit hold'em is described on the website as having a observation space of size 72 but is actually 52, it looks like it corresponds to the actual description on the RL card website "The state is represented as 52 cards and 2 elements of the chips of the players:". 

It looks like the descriptions for no limit and limit hold'em are switched on the website since the standard version is 72 which corresponds to what the RL card website says and what it is in the code base. 

you can check this as follows: 

```
from pettingzoo.classic import texas_holdem_no_limit_v5

env = texas_holdem_no_limit_v5.env(num_players=2)
env.reset()

print(len(env.observe(agent=env.agents[0])['observation']))
```

**Comment by jkterry1** [comment]
Hey, the docs should all be fixed now. Please let us know if they aren't.
