### ISSUE TITLE
Remove global/local rewards from pistonball

### ISSUE THREAD

**Issue by jkterry1** [PettingZoo-Team/PettingZoo#485]
The argument never made sense or worked, we disabled it and were thinking about removing it before (and the docs say this) and I've gotten multiple confused messages about it. If it's useless _and_ confusing people it needs to finally go.

**Comment by RyanNavillus** [comment]
I think the concept behind the argument makes sense, it's just implemented in a way that makes it hard to tell what it's doing or if it's correct. But allowing the user to reward agents that more directly influenced the ball's movement seems like a good feature. I think a better solution would be to just refactor and test the local/global reward.

**Comment by benblack769** [comment]
The current global/local logic can be handled with a wrapper. Something to consider.
