### ISSUE TITLE
Manual control test crashing on newer versions of macOS

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/PettingZoo#59]
When running manual control tests, using pynput, the games all crash with an `Illegal instruction: 4` error, indicating something wasn't built properly for macOS's new 64 bit features. This isn't pynput's fault either because it's a pure python package.

This also only happens with newer macs and macos catalina, which is the opposite of what is expected with illegal instruction 4 errors.

I have absolutely no idea what the problem here is.

**Comment by justinkterry** [comment]
@MarioJayakumar is this still a problem?

**Comment by MarioJayakumar** [comment]
I don't have this problem on my local machine, the manual tests seem to work fine.

**Comment by justinkterry** [comment]
It's fine on macos travis too right? Or can we not see due to the VM graphics problem?

**Comment by MarioJayakumar** [comment]
Well manual control on Travis OSX is only disabled on SISL and Gamma, so for every other environment it works fine
