### ISSUE TITLE
gamma/knights_archers_zombies performance improvements

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/PettingZoo#62]
KAZ runs slower than all the other gamma games, and seemingly needs a large amount of refactoring to be able to run at the same speed as them. The problem seems to either be due to the collision detection, or the tremendous numbers of different dictionaries and lists used to keep track of objects in the game.

**Comment by weepingwillowben** [comment]
#119 Fixes kaz problem to substantial degree. 

Biggest remaining issue is that KAZ and cooperative pong have an insanely high resolution observation space. Like, no one wants to process a 500x500 pixel image for such simple games. They first thing any real user will do is downsample the observation, so there is enormous wasted time processing it in high resolution form.

**Comment by weepingwillowben** [comment]
For context, all gamma games seem to spend at least 80% of their time rendering and processing observation, cutting resolution by  a factor of 4 and shrinking the corresponding observation space should increase performance by 2-3 times.
